export const enIpaRules = `
  ::Lower;
  $eiy = [e i y];
  $v = [a e i o u];
  $vy = [a e i o u y];
  $c = [b c d f g h j k l m n p q r s t v w x z];
  $boundary = [:^Letter:];
  $letter = [:Letter:];
  
  { a } $c e s $boundary > eɪ;
  { e } $c e s $boundary > iː;
  { i } $c e s $boundary > aɪ;
  { o } $c e s $boundary > oʊ;
  { u } $c e s $boundary > juː;
  { a } $c e $boundary > eɪ;
  { e } $c e $boundary > iː;
  { i } $c e $boundary > aɪ;
  { o } $c e $boundary > oʊ;
  { u } $c e $boundary > juː;
  { y } $c e > aɪ;
  { i n e } $boundary > ɪn;
  { i c e } $boundary > ɪs;
  
  ce } $boundary > s;
  ge } $boundary > dʒ;
  mb } $boundary > m;
  { as } $boundary > əs;
  { [a e o] n } $boundary > ən;
  { a } [m b l] $boundary > ə;
  ai } $boundary > aɪ;
  i { a } n > ə;
  
  ought > ɔːt;
  aught > ɔːt;
  ough { t > ɔː;
  ough > oʊ;
  augh > æf;
  tion > ʃən;
  sion > ʒən;
  cian > ʃən;
  tious > ʃəs;
  cious > ʃəs;
  ture > tʃə;
  sure > ʒə;
  cial > ʃəl;
  tial > ʃəl;
  ing > ɪŋ;
  all > ɔːl;
  full > fʊl;
  ch { [rɹl] > k;
  t [eɛ] { ch > k;
  cc { $eiy > ks;
  cc > k;
  ch > tʃ;
  sh > ʃ;
  th { $vy > ð;
  th > θ;
  ph > f;
  ng > ŋ;
  nk > ŋk;
  ck > k;
  wh { $vy > w;
  wh > hw;
  wr > r;
  kn > n;
  gn > n;
  ps > s;
  bt > t;
  dg > dʒ;
  qu > kw;
  x { $vy > ɡz;
  x > ks;
  ee > iː;
  ea { [drt] > e;
  ea > iː;
  ai > eɪ;
  ay > eɪ;
  ei > eɪ;
  ey > iː;
  oa > oʊ;
  oe > oʊ;
  oo { [kdg] > ʊ;
  oo > uː;
  ou { r > uː;
  ou > aʊ;
  ow { [ln] > aʊ;
  ow > oʊ;
  oi > ɔɪ;
  oy > ɔɪ;
  au > ɔː;
  aw > ɔː;
  ie { r > aɪ;
  ie > iː;
  ui > uː;
  ar { $v > æɹ;
  { a } r > ɑː;
  er { $v > ɛɹ;
  { e } r > ɜː;
  { i } r > ɜː;
  or { $v > ɔːɹ;
  { o } r > ɔː;
  { u } r > ɜː;
  { y } r > ɜː;
  { e s } $boundary > z;
  a > æ;
  e > ɛ;
  i { $c $vy > aɪ;
  { i } $boundary > i;
  i > ɪ;
  o { $c $vy > oʊ;
  o > ɒ;
  u e > uː;
  u > ʌ;
  y { $c } $boundary > i;
  y { $v > j;
  y > i;
  
  $v $c+ { [e ɛ] } $boundary > ;
  
  nn > n;
  rr > ɹ;
  dd > d;
  mm > m;
  ll > l;
  ss > s;
  ff > f;
  tt > t;
  pp > p;
  
  c { $eiy > s;
  c > k;
  g { $eiy > dʒ;
  { g h } $boundary > ;
  g > ɡ;
  j > dʒ;
  r > ɹ;
  s { $vy > z;
  { [eɛ] s } $boundary > z;
  [b d ɡ v ð z ʒ dʒ l m n ŋ ɹ] { s } $boundary > z;
  s > s;
  b > b;
  d > d;
  f > f;
  h > h;
  k > k;
  l > l;
  m > m;
  n > n;
  p > p;
  t > t;
  v > v;
  w > w;
  z > z;
`;
