export const frIpaRules = `
::Lower;

$vowel = [aàâäæeéèêëiîïoôœuûüùy];
$cons = [bcdfghjklmnpqrstvwxz];
$soft = [eéèêëiîïy];
$nasal_trigger = [^$vowel n m];
$boundary = [:^Letter:];

femme > fam;
monsieur > məsjø;
ville > vil;
mille > mil;
tranquille > tʁɑ̃kil;
ille } $boundary > ij;
oignon > ɔɲɔ̃;
second > sgɔ̃;
examen > ɛgzamɛ̃;
chœur > kœʁ;
chorale > kɔʁal;
chaos > kao;
yacht > jɔt;

œu } d > œ;
œu } f > œ;
œu } r > œ;
œu > ø;
  
tien } $boundary > tjɛ̃;
sien } $boundary > sjɛ̃;
rien } $boundary > ʁjɛ̃;
bien } $boundary > bjɛ̃;
moyen } $boundary > mwajɛ̃;

ien } $nasal_trigger > jɛ̃;
yen } $nasal_trigger > jɛ̃;
ain } $nasal_trigger > ɛ̃;
aim } $nasal_trigger > ɛ̃;
ein } $nasal_trigger > ɛ̃;
eim } $nasal_trigger > ɛ̃;
oin } $nasal_trigger > wɛ̃;
aon } $nasal_trigger > ɑ̃;
un } $nasal_trigger > œ̃;
um } $nasal_trigger > œ̃;
ontp > ɔ̃p;
on } $nasal_trigger > ɔ̃;
om } $nasal_trigger > ɔ̃;
ian } $nasal_trigger > jɑ̃;
ean } $nasal_trigger > ɑ̃;
an } $nasal_trigger > ɑ̃;
am } $nasal_trigger > ɑ̃;
en } $nasal_trigger > ɑ̃;
em } $nasal_trigger > ɑ̃;
in } $nasal_trigger > ɛ̃;
im } $nasal_trigger > ɛ̃;
yn } $nasal_trigger > ɛ̃;
ym } $nasal_trigger > ɛ̃;

ault } $boundary > o;
eot } $boundary > o;
eau > o;
ea > a;
au > o;
eu > ø;
ouy > wi;
bourg } $boundary > buʁ;
ou > u;
oi > wa;
oy } $boundary > wa;
oy > waj;
ui > ɥi;
ai > ɛ;
ay > ɛj;
eill > ɛj;
ei > ɛ;
ey > ɛj;
chr > kʁ;
chl > kl;
sch > ʃ;
ch > ʃ;
sh > ʃ;
ph > f;
th > t;
gn > ɲ;
lille > lil;
ill } $vowel > ij;
ill > ij;
il } $boundary > ij;
gu } $soft > g;
cqu > k;
qu > k;
q > k;
cc } $soft > ks;
cc > k;
c } $soft > s;
c > k;
g } $soft > ʒ;
g > g;
ç > s;
$vowel { s } $vowel > z;
ès } $boundary > ɛs;
s } $boundary > ;
x } $boundary > ;
t } $boundary > ;
d } $boundary > ;
p } $boundary > ;
es } $boundary > ;
ec } $boundary > ɛk;
el } $boundary > ɛl;
ie } $boundary > i;
ier } $boundary > je;
ers } $boundary > e;
ess } $boundary > ɛs;
ert } $boundary > ɛʁ;
ett } $boundary > ɛt;
ell } $boundary > ɛl;
err } $boundary > ɛʁ;
err > ɛʁ;
er } $cons > ɛʁ;
er } $boundary > e;
e } $boundary > ;
bb > b;
dd > d;
ff > f;
ll > l;
mm > m;
nn > n;
pp > p;
rr > ʁ;
ss > s;
tt > t;
vv > v;
zz > z;
i } $vowel > j;
a > a;
à > a;
â > ɑ;
ä > a;
æ > e;
b > b;
ette } $boundary > ɛt;
elle } $boundary > ɛl;
esse } $boundary > ɛs;
enne } $boundary > ɛn;
ose } $boundary > oz;
ex > ɛks;
e > ə;
é > e;
è > ɛ;
ê > ɛ;
ë > ɛ;
f > f;
h > ;
i > i;
î > i;
ï > i;
j > ʒ;
k > k;
l > l;
m > m;
n > n;
o > ɔ;
ô > o;
ö > œ;
œ > œ;
p > p;
r > ʁ;
v > v;
w > v;
x > ks;
y } $vowel > j;
y > i;
z > z;
u > y;
û > y;
ü > y;
ù > y;
`;
