export const frIpaRules = `
::Lower;

femme > fam;
monsieur > məsjø;
ville > vil;
mille > mil;
tranquille > tʁɑ̃kil;
ille } [:^Letter:] > ij;
oignon > ɔɲɔ̃;
second > sgɔ̃;
examen > ɛgzamɛ̃;
chœur > kœʁ;
chorale > kɔʁal;
chaos > kao;
yacht > jɔt;

œu } d > œ;
œu } f > œ;
œu } r > œ;
œu > ø;

tien } [:^Letter:] > tjɛ̃;
sien } [:^Letter:] > sjɛ̃;
rien } [:^Letter:] > ʁjɛ̃;
bien } [:^Letter:] > bjɛ̃;
moyen } [:^Letter:] > mwajɛ̃;

ien } [^aàâäæeéèêëiîïoôœuûüùynm] > jɛ̃;
yen } [^aàâäæeéèêëiîïoôœuûüùynm] > jɛ̃;
ain } [^aàâäæeéèêëiîïoôœuûüùynm] > ɛ̃;
aim } [^aàâäæeéèêëiîïoôœuûüùynm] > ɛ̃;
ein } [^aàâäæeéèêëiîïoôœuûüùynm] > ɛ̃;
eim } [^aàâäæeéèêëiîïoôœuûüùynm] > ɛ̃;
oin } [^aàâäæeéèêëiîïoôœuûüùynm] > wɛ̃;
aon } [^aàâäæeéèêëiîïoôœuûüùynm] > ɑ̃;
un } [^aàâäæeéèêëiîïoôœuûüùynm] > œ̃;
um } [^aàâäæeéèêëiîïoôœuûüùynm] > œ̃;
ontp > ɔ̃p;
on } [^aàâäæeéèêëiîïoôœuûüùynm] > ɔ̃;
om } [^aàâäæeéèêëiîïoôœuûüùynm] > ɔ̃;
ian } [^aàâäæeéèêëiîïoôœuûüùynm] > jɑ̃;
ean } [^aàâäæeéèêëiîïoôœuûüùynm] > ɑ̃;
an } [^aàâäæeéèêëiîïoôœuûüùynm] > ɑ̃;
am } [^aàâäæeéèêëiîïoôœuûüùynm] > ɑ̃;
en } [^aàâäæeéèêëiîïoôœuûüùynm] > ɑ̃;
em } [^aàâäæeéèêëiîïoôœuûüùynm] > ɑ̃;
in } [^aàâäæeéèêëiîïoôœuûüùynm] > ɛ̃;
im } [^aàâäæeéèêëiîïoôœuûüùynm] > ɛ̃;
yn } [^aàâäæeéèêëiîïoôœuûüùynm] > ɛ̃;
ym } [^aàâäæeéèêëiîïoôœuûüùynm] > ɛ̃;

ault } [:^Letter:] > o;
eot } [:^Letter:] > o;
eau > o;
ea > a;
au > o;
eu > ø;
ouy > wi;
bourg } [:^Letter:] > buʁ;
ou > u;
oi > wa;
oy } [:^Letter:] > wa;
oy > waj;
ui > ɥi;
ai > ɛ;
ay > ɛj;
eill > ɛj;
ei > ɛ;
ey > ɛj;
chr > kʁ;
chl > kl;
sch > ʃ;
ch > ʃ;
sh > ʃ;
ph > f;
th > t;
gn > ɲ;
lille > lil;
ill } [aàâäæeéèêëiîïoôœuûüùy] > ij;
ill > ij;
il } [:^Letter:] > ij;
gu } [eéèêëiîïy] > g;
cqu > k;
qu > k;
q > k;
cc } [eéèêëiîïy] > ks;
cc > k;
c } [eéèêëiîïy] > s;
c > k;
g } [eéèêëiîïy] > ʒ;
g > g;
ç > s;
[aàâäæeéèêëiîïoôœuûüùy] { s } [aàâäæeéèêëiîïoôœuûüùy] > z;
ès } [:^Letter:] > ɛs;
s } [:^Letter:] > ;
x } [:^Letter:] > ;
t } [:^Letter:] > ;
d } [:^Letter:] > ;
p } [:^Letter:] > ;
es } [:^Letter:] > ;
ec } [:^Letter:] > ɛk;
el } [:^Letter:] > ɛl;
ie } [:^Letter:] > i;
ier } [:^Letter:] > je;
ers } [:^Letter:] > e;
ess } [:^Letter:] > ɛs;
ert } [:^Letter:] > ɛʁ;
ett } [:^Letter:] > ɛt;
ell } [:^Letter:] > ɛl;
err } [:^Letter:] > ɛʁ;
err > ɛʁ;
er } [bcdfghjklmnpqrstvwxz] > ɛʁ;
er } [:^Letter:] > e;
e } [:^Letter:] > ;
bb > b;
dd > d;
ff > f;
ll > l;
mm > m;
nn > n;
pp > p;
rr > ʁ;
ss > s;
tt > t;
vv > v;
zz > z;
i } [aàâäæeéèêëiîïoôœuûüùy] > j;
a > a;
à > a;
â > ɑ;
ä > a;
æ > e;
b > b;
ette } [:^Letter:] > ɛt;
elle } [:^Letter:] > ɛl;
esse } [:^Letter:] > ɛs;
enne } [:^Letter:] > ɛn;
ose } [:^Letter:] > oz;
ex > ɛks;
e > ə;
é > e;
è > ɛ;
ê > ɛ;
ë > ɛ;
f > f;
h > ;
i > i;
î > i;
ï > i;
j > ʒ;
k > k;
l > l;
m > m;
n > n;
o > ɔ;
ô > o;
ö > œ;
œ > œ;
p > p;
r > ʁ;
v > v;
w > v;
x > ks;
y } [aàâäæeéèêëiîïoôœuûüùy] > j;
y > i;
z > z;
u > y;
û > y;
ü > y;
ù > y;
`;
