export const heIpaMap: Record<string, string> = {
  ירושלים: "jeʁuʃaˈlajim",
  "תל אביב יפו": "tel aˈviv ˈjafo",
  חיפה: "χeiˈfa",
  בנק: "bank",
  ישראל: "jisʁaˈʔel",
  פועלים: "poʔaˈlim",
  חברה: "ˈχevʁa",
  אילת: "eiˈlat",
  אשדוד: "aʃˈdod",
  נתניה: "netaˈnja",
  חולון: "χoˈlon",
  בני: "bne",
  ברק: "bʁak",
  רמת: "ʁaˈmat",
  גן: "ɡan",
  הרצליה: "heʁt͡seˈlija",
  כפר: "kfaʁ",
  סבא: "ˈsava",
  ראשון: "ʁiˈʃon",
  לציון: "let͡siˈjon",
  פתח: "ˈpetaχ",
  תקווה: "tikˈva",
  טבריה: "tveˈʁija",
  צפת: "t͡sfat",
  באר: "beˈʔeʁ",
  שבע: "ˈʃeva",
  נצרת: "naˈt͡seʁet",
  "בית שמש": "bet ˈʃemeʃ",
  "מודיעין מכבים רעות": "modiˈʕin makaˈbim ʁeˈʕut",
  "מעלה אדומים": "maʕaˈle aduˈmim",
  "אל על": "el al",
  "ים המלח": "jam haˈmelaχ",
  אברהם: "avʁaˈham",
  יצחק: "jit͡sˈχak",
  כהן: "koˈhen",
  שרה: "saˈʁa",
  רבקה: "ʁivˈka",
  לוי: "leˈvi",
  דוד: "daˈvid",
  משה: "moˈʃe",
  מזרחי: "mizʁaˈχi",
  מרים: "miʁˈjam",
  לאה: "leˈʔa",
  פרץ: "ˈpeʁet͡s",
  יונתן: "jonaˈtan",
  שמואל: "ʃmuˈʔel",
  נועה: "ˈnoʕa",
  חנה: "ˈχana",
  פרידמן: "ˈfʁidman",
  איתי: "iˈtaj",
  אלכסנדר: "alekˈsandeʁ",
  כץ: "kat͡s",
  מאיה: "ˈmaja",
  שלומית: "ʃloˈmit",
  אשכנזי: "aʃkenaˈzi",
  גיא: "ɡaj",
  בנימין: "binjaˈmin",
  ביטון: "ˈbiton",
  תמר: "taˈmaʁ",
  בתיה: "batˈja",
  שפירא: "ʃaˈpiʁa",
  רועי: "ʁoˈʕi",
  יהודה: "jehuˈda",
  מלכה: "malˈka",
  עדי: "aˈdi",
  רחל: "ʁaˈχel",
  גולדשטיין: "ˈɡoldʃtejn",
  דניאל: "daniˈʔel",
  אהרון: "ahaˈʁon",
  שגב: "ˈseɡev",
  הילה: "hiˈla",
  חדד: "χaˈdad",
  יובל: "juˈval",
  ברקוביץ: "ˈbeʁkovit͡s",
  רוני: "ʁoˈni",
  שירה: "ʃiˈʁa",
  דיין: "daˈjan",
  מתן: "maˈtan",
  פנחס: "pinˈχas",
  אזולאי: "azuˈlaj",
  אילנה: "iˈlana",
  וייס: "vajs",
  עומר: "ˈʕomeʁ",
  שלמה: "ʃloˈmo",
  גבאי: "ɡaˈbaj",
  מיכל: "miˈχal",
  זהבה: "zehaˈva",
  שוורץ: "ʃvaʁt͡s",
  תעשייה: "taʕasiˈja",
  אווירית: "aviˈʁit",
  שירותי: "ʃeʁuˈtej",
  בריאות: "bʁiˈʔut",
  כללית: "klaˈlit",
  חברת: "χevˈʁat",
  חשמל: "χaʃˈmal",
  לאומי: "leʔuˈmi",
  נתיבי: "netiˈvej",
  אוויר: "aˈviʁ",
  שופרסל: "ʃufeʁˈsal",
  השקעות: "haʃkaˈʕot",
  שטראוס: "ʃtʁaˈus",
  גרופ: "ɡʁup",
  ניהול: "niˈhul",
  טבע: "ˈteva",
  תעשיות: "taʕasiˈjot",
  פרמצבטיות: "faʁmat͡sevˈtijot",
  בעירבון: "beʕeʁaˈvon",
  מוגבל: "muɡˈbal",
  סלקום: "ˈselkum",
  פרטנר: "ˈpaʁtneʁ",
  אסם: "ˈosem",
  מפעלי: "mifʕaˈlej",
  מקורות: "mekoˈʁot",
  המים: "haˈmajim",
  לאומית: "leʔuˈmit",
  רכבת: "ʁaˈkevet",
  צבאית: "t͡svaˈʔit",
  דיסקונט: "disˈkont",
  מגדל: "miɡˈdal",
  ביטוח: "biˈtuʔaχ",
  הראל: "haʁˈʔel",
  שירותים: "ʃeʁuˈtim",
  פיננסיים: "fiˈnansijim",
  סבג: "saˈbaɡ",
  פלאפון: "peleˈfon",
  תקשורת: "tikˈʃoʁet",
  "ראשון לציון": "ʁiˈʃon let͡siˈjon",
  "פתח תקווה": "ˈpetaχ tikˈva",
  "בני ברק": "bne bʁak",
  "רמת גן": "ʁaˈmat ɡan",
  "כפר סבא": "kfaʁ ˈsava",
  חדרה: "χadeˈʁa",
  רחובות: "ʁeχoˈvot",
  "בת ים": "bat jam",
  אשקלון: "aʃkeˈlon",
  רעננה: "ʁaʕaˈnana",
  נהריה: "nahaˈʁija",
  "קריית עתא": "kiʁˈjat ˈata",
  גבעתיים: "ɡivʕaˈtajim",
  עכו: "ˈako",
  רמלה: "ʁamˈla",
  לוד: "lod",
  "רמת השרון": "ʁaˈmat haʃaˈʁon",
  "הוד השרון": "hod haʃaˈʁon",
  אריאל: "aʁiˈʔel",
  "קריית גת": "kiʁˈjat ɡat",
  "קריית מוצקין": "kiʁˈjat ˈmot͡skin",
  "קריית ביאליק": "kiʁˈjat biˈjalik",
  "קריית ים": "kiʁˈjat jam",
  עפולה: "aˈfula",
  כרמיאל: "kaʁmiˈʔel",
  "נוף הגליל": "nof haɡaˈlil",
  נועם: "ˈnoʕam",
  איתמר: "itaˈmaʁ",
  לביא: "laˈvi",
  יוסף: "joˈsef",
  אורי: "uˈʁi",
  איתן: "eiˈtan",
  יהונתן: "jehonaˈtan",
  אביגיל: "aviˈɡajil",
  טליה: "talˈja",
  יעל: "jaˈʕel",
  אלה: "eˈla",
  דאהן: "daˈhan",
  אגמון: "aɡˈmon",
  אוחיון: "oχaˈjon",
  עמר: "aˈmaʁ",
  ממן: "maˈman",
  סויסה: "suiˈsa",
  שורץ: "ʃvaʁt͡s",
  גולן: "ɡoˈlan",
  שרון: "ʃaˈʁon",
  בזק: "ˈbezek",
  אמדוקס: "ˈamdoks",
  "צ'ק פוינט": "t͡ʃek pojnt",
  וויקס: "viks",
  מאנדיי: "ˈmandej",
  אלביט: "ˈelbit",
  מערכות: "maʕaʁaˈχot",
  תנובה: "tnuˈva",
  הפועלים: "hapoʔaˈlim",
  "סופר-פארם": "ˈsupeʁ faʁm",
  מכבי: "maˈkabi",
  מאוחדת: "meʔuˈχedet",
  ויזה: "ˈviza",
  ישראכרט: "isʁaˈkaʁt",
  פז: "paz",
  דלק: "ˈdelek",
  סונול: "ˈsonol",
  הוט: "hot",
  יס: "jes",
  "רמי לוי": "ˈʁami leˈvi",
  קסטרו: "ˈkastʁo",
  פוקס: "foks",
  "אלטשולר שחם": "ˈaltʃuleʁ ˈʃaχam",
  פסגות: "psaˈɡot",
  "מיטב דש": "meiˈtav daʃ",
  הכשרה: "haχʃaˈʁa",
  כלל: "klal",
  "מנורה מבטחים": "menoˈʁa mivtaˈχim",
  איילון: "ajaˈlon",
  צים: "t͡sim",
  רפאל: "ʁefaˈʔel",
  סייברארק: "ˈsajbeʁaʁk",
  נייס: "najs",
  טאבולה: "taˈbula",
  אאוטבריין: "ˈautbʁejn",
  פייבר: "ˈfajveʁ",
  למונייד: "ˈlemonejd",
  גט: "ɡet",
  פנגו: "ˈpanɡo",
  מובילאיי: "ˈmobilaj",
  מטולה: "metuˈla",
  שדרות: "sdeˈʁot",
  דימונה: "diˈmona",
  ירוחם: "jeʁuˈχam",
  קצרין: "kat͡sˈʁin",
  "זכרון יעקב": "ziχˈʁon jaʕaˈkov",
  בנימינה: "binjaˈmina",
  "פרדס חנה": "paʁˈdes ˈχana",
  כרכור: "kaʁˈkuʁ",
  אופקים: "ofaˈkim",
  נתיבות: "netiˈvot",
  רהט: "ˈʁahat",
  "קרית שמונה": "kiʁˈjat ʃmoˈna",
  חריש: "χaˈʁiʃ",
  "יקנעם עילית": "jokneˈʕam iˈlit",
  נשר: "ˈneʃeʁ",
  "טירת כרמל": "tiˈʁat kaʁˈmel",
  "מעלות תרשיחא": "maʕaˈlot taʁˈʃiχa",
  "מגדל העמק": "miɡˈdal haˈʕemek",
  "בית שאן": "bet ʃeˈʔan",
  טייבה: "ˈtajbe",
  טירה: "ˈtiʁa",
  "כפר קאסם": "kfaʁ ˈkasem",
  שפרעם: "ʃfaʁˈʕam",
  "אום אל פחם": "um al faχm",
  "באר יעקב": "beˈʔeʁ jaʕaˈkov",
  "גבעת שמואל": "ɡivˈʕat ʃmuˈʔel",
  "נס ציונה": "nes t͡siˈjona",
  "ראש העין": "ʁoʃ haˈʕajin",
  "קרית אונו": "kiʁˈjat ˈono",
  "יהוד מונוסון": "jeˈhud monosen",
  מיכאל: "miχaˈʔel",
  גבריאל: "ɡavʁiˈʔel",
  אליהו: "eliˈjahu",
  שמעון: "ʃimˈʕon",
  עידן: "iˈdan",
  עומרי: "omˈʁi",
  אסף: "aˈsaf",
  אלעד: "elˈʕad",
  אורן: "ˈoʁen",
  אלון: "aˈlon",
  ארז: "ˈeʁez",
  עמית: "aˈmit",
  תומר: "ˈtomeʁ",
  מאור: "maˈʔoʁ",
  ליאור: "liˈʔoʁ",
  שירן: "ʃiˈʁan",
  אגם: "aˈɡam",
  חזן: "χaˈzan",
  אוחנה: "oˈχana",
  "אברג'יל": "abaʁˈd͡ʒil",
  קורן: "koˈʁen",
  "ברקוביץ'": "ˈbeʁkovit͡ʃ",
  קופרמן: "ˈkupeʁman",
  גולדברג: "ˈɡoldbeʁɡ",
  רוזנטל: "ˈʁozental",
  זפרני: "zafaˈʁani",
  עטיה: "aˈtija",
  קדוש: "kaˈdoʃ",
  אלבז: "elˈbaz",
  וקנין: "vakˈnin",
  טולדנו: "toleˈdano",
  אדרי: "edˈʁi",
  אינטל: "ˈintel",
  מיקרוסופט: "ˈmajkʁosoft",
  גוגל: "ˈɡuɡel",
  אפל: "ˈapel",
  אמזון: "ˈamazon",
  מטא: "ˈmeta",
  מלאנוקס: "melaˈnoks",
  פלייטיקה: "plejˈtika",
  וויז: "vejz",
  מוביט: "ˈmubit",
  אורמת: "oʁˈmat",
  גילת: "ɡiˈlat",
  נובה: "ˈnova",
  תדיראן: "tadiˈʁan",
  אלקטרה: "eˈlektʁa",
  יוחננוף: "joχanaˈnof",
  "חצי חינם": "χaˈt͡si χiˈnam",
  ויקטורי: "ˈviktoʁi",
  "מחסני השוק": "maχsaˈnej haˈʃuk",
  ישרוטל: "isʁoˈtel",
  פתאל: "faˈtal",
  דן: "dan",
  ארקיע: "aʁˈkiʕa",
  ישראייר: "isʁaˈjeʁ",
  "בנק לאומי": "bank leʔuˈmi",
  "בנק הפועלים": "bank hapoʔaˈlim",
  "בנק דיסקונט": "bank disˈkont",
  "בנק מזרחי טפחות": "bank mizʁaˈχi tfaˈχot",
  הבינלאומי: "habejnleʔuˈmi",
  יבנה: "ˈjavne",
  ערד: "aˈʁad",
  "מצפה רמון": "mit͡sˈpe ʁaˈmon",
  "קריית מלאכי": "kiʁˈjat malʔaˈχi",
  סחנין: "saχˈnin",
  "אבו גוש": "ˈabu ɡoʃ",
  "אור יהודה": "oʁ jehuˈda",
  אזור: "aˈzoʁ",
  "גני תקווה": "ɡaˈnej tikˈva",
  "כפר שמריהו": "kfaʁ ʃmaʁˈjahu",
  סביון: "savˈjon",
  שלומי: "ʃloˈmi",
  "חצור הגלילית": "χaˈt͡soʁ haɡliˈlit",
  צמח: "ˈt͡semaχ",
  אפיקים: "afiˈkim",
  כנרת: "kiˈneʁet",
  דגניה: "dɡanˈja",
  אילון: "ejaˈlon",
  שפיים: "ʃfaˈjim",
  געש: "ˈɡaʕaʃ",
  יקום: "jaˈkum",
  רשפון: "ʁiʃˈpon",
  "כפר ויתקין": "kfaʁ vitˈkin",
  מכמורת: "miχˈmoʁet",
  קיסריה: "kejsaˈʁija",
  "אור עקיבא": "oʁ aˈkiva",
  עתלית: "atˈlit",
  טבעון: "tivˈʕon",
  יגור: "jaˈɡuʁ",
  דליה: "dalˈja",
  עוספיא: "isafˈja",
  ריינה: "ˈʁejne",
  יפיע: "jaˈfiʕa",
  אכסאל: "iχˈsal",
  "כפר כנא": "kfaʁ kaˈna",
  עראבה: "aˈʁaba",
  נחף: "ˈnaχaf",
  "מג'ד אל כרום": "mad͡ʒd al kʁum",
  יובלים: "juvaˈlim",
  משגב: "misˈɡav",
  אבי: "aˈvi",
  ירון: "jaˈʁon",
  גדי: "ˈɡadi",
  אהוד: "eˈhud",
  עמוס: "aˈmos",
  גדעון: "ɡidˈʕon",
  שאול: "ʃaˈʔul",
  רון: "ʁon",
  תמיר: "taˈmiʁ",
  גל: "ɡal",
  שיר: "ʃiʁ",
  נוי: "noj",
  אור: "oʁ",
  בר: "baʁ",
  מור: "moʁ",
  סתיו: "stav",
  אביב: "aˈviv",
  פלג: "ˈpeleɡ",
  ארבל: "aʁˈbel",
  כרמל: "kaʁˈmel",
  ירדן: "jaʁˈden",
  מעיין: "maʕaˈjan",
  ניר: "niʁ",
  חן: "χen",
  שי: "ʃaj",
  דור: "doʁ",
  יצחקי: "jit͡sˈχaki",
  כהנא: "kahaˈna",
  אטיאס: "aˈtijas",
  חלפון: "χalˈfon",
  מועלם: "muˈʕalem",
  שרעבי: "ʃaʁˈʕabi",
  צברי: "t͡saˈbaʁi",
  קאפח: "kaˈpaχ",
  לוין: "leˈvin",
  פריד: "fʁid",
  גרוס: "ɡʁos",
  קליין: "klajn",
  בלום: "blum",
  רוזן: "ˈʁozen",
  פלד: "ˈpeled",
  שדה: "saˈde",
  גלבוע: "ɡilˈboʕa",
  גולף: "ɡolf",
  "המשביר לצרכן": "hamaʃˈbiʁ lat͡saʁˈχan",
  סטימצקי: "stimat͡sˈki",
  "צומת ספרים": "ˈt͡somet sfaˈʁim",
  "מקס סטוק": "maks stok",
  איקאה: "iˈkeʔa",
  שילב: "ʃiˈlav",
  עלית: "iˈlit",
  טרה: "ˈtaʁa",
  יטבתה: "jotvaˈta",
  זוגלובק: "zoɡˈlovek",
  "אנג'ל": "anˈd͡ʒel",
  ברמן: "ˈbeʁman",
  אגד: "ˈeɡed",
  קווים: "kaˈvim",
  סופרבוס: "ˈsupeʁbus",
  מטרופולין: "metʁopoˈlin",
  "טרמינל איקס": "ˈteʁminal iks",
  מיתר: "mejˈtaʁ",
  להבים: "lehaˈvim",
  חולתה: "χulaˈta",
  "יסוד המעלה": "jeˈsod hamaʕaˈla",
  "ראש פינה": "ʁoʃ ˈpina",
  "אלפי מנשה": "alˈfe menaˈʃe",
  "קרני שומרון": "kaʁˈnej ʃomˈʁon",
  קדומים: "kduˈmim",
  אפרת: "efˈʁat",
  "גוש עציון": "ɡuʃ et͡sˈjon",
  "ביתר עילית": "bejˈtaʁ iˈlit",
  "מעלה אפרים": "maʕaˈle efˈʁajim",
  "בית אריה": "bet aʁˈje",
  שילה: "ʃiˈlo",
  עלי: "eˈli",
  תקוע: "tkoˈʕa",
  נוקדים: "nokˈdim",
  "כפר אדומים": "kfaʁ aduˈmim",
  "מצפה יריחו": "mit͡sˈpe jeʁiˈχo",
  "ים כנרת": "jam kiˈneʁet",
  "הים התיכון": "haˈjam hatiˈχon",
  "ים סוף": "jam suf",
  הירדן: "hajaʁˈden",
  החרמון: "haχeʁˈmon",
  מצדה: "met͡saˈda",
  "עין גדי": "ejn ˈɡedi",
  קומראן: "kumˈʁan",
  "בית אלפא": "bet ˈalfa",
  "תל דן": "tel dan",
  "תל חצור": "tel χaˈt͡soʁ",
  "תל מגידו": "tel meɡiˈdo",
  עבדת: "avˈdat",
  שבטה: "ʃivˈta",
  ממשית: "mamˈʃit",
  סוסיה: "susiˈja",
  נעמי: "noʕoˈmi",
  רות: "ʁut",
  אסתר: "esˈteʁ",
  מרדכי: "moʁdeˈχaj",
  יהושע: "jehoˈʃuʕa",
  אליעזר: "eliˈʕezeʁ",
  יעקב: "jaʕaˈkov",
  דינה: "diˈna",
  ראובן: "ʁeʔuˈven",
  יששכר: "jisaˈsaʁ",
  זבולון: "zvuˈlun",
  נפתלי: "naftaˈli",
  גד: "ɡad",
  אשר: "aˈʃeʁ",
  מנשה: "menaˈʃe",
  חיים: "χaˈjim",
  שלום: "ʃaˈlom",
  מאיר: "meˈʔiʁ",
  יחיאל: "jeχiˈʔel",
  עקיבא: "aˈkiva",
  צבי: "t͡svi",
  זאב: "zeˈʔev",
  דוב: "dov",
  איילה: "ajaˈla",
  צביה: "t͡sviˈja",
  פנינה: "pniˈna",
  שושנה: "ʃoʃaˈna",
  ורד: "ˈveʁed",
  סיגלית: "siɡaˈlit",
  כלנית: "kalaˈnit",
  מרגלית: "maʁɡaˈlit",
  יהלום: "jahaˈlom",
  ענבל: "inˈbal",
  מיטל: "mejˈtal",
  רויטל: "ʁeviˈtal",
  אורטל: "oʁˈtal",
  ליטל: "liˈtal",
  טלי: "ˈtali",
  גלי: "ˈɡali",
  אורלי: "oʁˈli",
  יפעת: "jifˈʕat",
  אוסנת: "osˈnat",
  עינת: "ejˈnat",
  הארץ: "haˈʔaʁet͡s",
  "ידיעות אחרונות": "jediˈʕot aχʁoˈnot",
  מעריב: "maʕaˈʁiv",
  "ישראל היום": "jisʁaˈʔel haˈjom",
  גלובס: "ɡlobs",
  כלכליסט: "kalkaˈlist",
  "דה מרקר": "de ˈmaʁkeʁ",
  קשת: "ˈkeʃet",
  רשת: "ˈʁeʃet",
  כאן: "kan",
  טמפו: "ˈtempo",
  "יקבי כרמל": "jikˈvej kaʁˈmel",
  "רמת הגולן": "ʁaˈmat haɡoˈlan",
  טבעול: "tivˈʕol",
  "סלטי צבר": "salaˈtej t͡saˈbaʁ",
  אחלה: "ˈaχla",
  "קבוצת חג'ג'": "kvuˈt͡sat χaˈd͡ʒad͡ʒ",
  "שיכון ובינוי": "ʃiˈkun uviˈnuj",
  "אפריקה ישראל": "ˈafʁika jisʁaˈʔel",
  "דניה סיבוס": "ˈdanja ˈsibus",
  "סולל בונה": "soˈlel boˈne",
  הפניקס: "hafeˈniks",
  "ביטוח ישיר": "biˈtuʔaχ jaˈʃiʁ",
  שירביט: "ʃiʁˈbit",
  מגדלור: "miɡdaˈloʁ",
  "טיב טעם": "tiv ˈtaʕam",
  קופיקס: "ˈkofiks",
  ארומה: "aˈʁoma",
  גרג: "ɡʁeɡ",
  לנדוור: "ˈlandveʁ",
  "מקס ברנר": "maks ˈbʁeneʁ",
  "הר חברון": "haʁ χevˈʁon",
  "בקעת הירדן": "bikˈʕat hajaʁˈden",
  "עמק יזרעאל": "ˈemek jizʁeˈʔel",
  "גליל עליון": "ɡaˈlil elˈjon",
  "גליל תחתון": "ɡaˈlil taχˈton",
  שפלה: "ʃfeˈla",
  נגב: "ˈneɡev",
  ערבה: "aʁaˈva",
  "מפרץ חיפה": "mifˈʁat͡s χejˈfa",
  "גוש דן": "ɡuʃ dan",
  "יהודה ושומרון": "jehuˈda veʃomˈʁon",
  "כפר יונה": "kfaʁ ˈjona",
  "אבן יהודה": "ˈeven jehuˈda",
  "תל מונד": "tel mond",
  "קדימה צורן": "kaˈdima t͡soˈʁan",
  פרדסיה: "paʁdesˈja",
  "גני עם": "ɡaˈnej am",
  חופית: "χoˈfit",
  "מבשרת ציון": "mevaˈseʁet t͡siˈjon",
  "פסגת זאב": "pisˈɡat zeˈʔev",
  גילה: "ɡiˈla",
  "הר חומה": "haʁ χoˈma",
  תלפיות: "talpiˈjot",
  רחביה: "ʁeχavˈja",
  "מאה שערים": "ˈmeʔa ʃeʕaˈʁim",
  "מחנה יהודה": "maχaˈne jehuˈda",
  פלורנטין: "floʁenˈtin",
  "נווה צדק": "neˈve ˈt͡sedek",
  "רמת החייל": "ʁaˈmat haχaˈjal",
  צהלה: "t͡sahaˈla",
  אפקה: "afaˈka",
  אביתר: "evjaˈtaʁ",
  ישי: "jiˈʃaj",
  בועז: "ˈboʕaz",
  חגי: "χaˈɡaj",
  עובדיה: "ovaˈdja",
  זכריה: "zχaʁˈja",
  צפניה: "t͡sfanˈja",
  חבקוק: "χavaˈkuk",
  נחום: "naˈχum",
  יונה: "joˈna",
  הושע: "hoˈʃeʕa",
  יואל: "joˈʔel",
  אליה: "eliˈja",
  אלישע: "eliˈʃa",
  יפתח: "jifˈtaχ",
  שמשון: "ʃimˈʃon",
  דבורה: "dvoˈʁa",
  אבישג: "aviˈʃaɡ",
  "בת שבע": "bat ˈʃeva",
  נעמה: "naʕaˈma",
  צפורה: "t͡sipoˈʁa",
  אלישבע: "eliˈʃeva",
  יוכבד: "joˈχeved",
  הגר: "haˈɡaʁ",
  קטורה: "ktuˈʁa",
  רחב: "ʁaˈχav",
  ימימה: "jemiˈma",
  קציעה: "kt͡siˈʕa",
  שפרה: "ʃifˈʁa",
  פועה: "puˈʕa",
  "הכשרת הישוב": "haχʃaˈʁat hajiˈʃuv",
  עזריאלי: "azʁiˈʔeli",
  מליסרון: "melisˈʁon",
  "אלוני חץ": "aˈloni χet͡s",
  "גב ים": "ɡav jam",
  "ריט 1": "ʁit eˈχad",
  מבנה: "mivˈne",
  "קבוצת דלק": "kvuˈt͡sat ˈdelek",
  בזן: "baˈzan",
  "פז נפט": "paz ˈneft",
  "שפיר הנדסה": "ʃaˈfiʁ handaˈsa",
  "אלקטרה מוצרי צריכה": "eˈlektʁa mut͡saˈʁej t͡sʁiˈχa",
  דיפלומט: "diploˈmat",
  "וילי פוד": "ˈvili fud",
  כרמית: "kaʁˈmit",
  סנו: "ˈsano",
  קליל: "kˈlil",
  "רב בריח": "ʁav baˈʁiʔaχ",
  "אבן קיסר": "ˈeven kejˈsaʁ",
  "דלתות פנדור": "dlaˈtot panˈdoʁ",
  טמבור: "tamˈbuʁ",
  נירלט: "niʁˈlat",
  יעקבי: "jaʕaˈkovi",
  "פוקס ויזל": "foks ˈvizel",
  "גולף אנד קו": "ɡolf end ko",
  עדיקה: "aˈdika",
  רנואר: "ʁenuˈaʁ",
  אלדן: "elˈdan",
  "שלמה סיקסט": "ʃloˈmo sikst",
  הרץ: "heʁt͡s",
  אוויס: "ˈavis",
  אלבר: "elˈbaʁ",
  כלמוביל: "kolmoˈbil",
  "צמפיון מוטורס": "ˈt͡ʃempjon ˈmotoʁs",
  "דלק רכב": "ˈdelek ˈʁeχev",
  קרסו: "kaˈʁaso",
  סמלת: "samˈlat",
  "מאיר חברה למכוניות": "meˈʔiʁ ˈχevʁa lmeχoniˈjot",
  הודו: "ˈhodu",
  סין: "sin",
  צרפת: "t͡saʁˈfat",
  גרמניה: "ɡeʁˈmanja",
  אנגליה: "ˈanɡlija",
  ספרד: "sfaˈʁad",
  איטליה: "iˈtalja",
  יוון: "jaˈvan",
  מצרים: "mit͡sˈʁajim",
  לבנון: "lvaˈnon",
  סוריה: "ˈsuʁja",
  עיראק: "iˈʁak",
  איראן: "iˈʁan",
  תימן: "tejˈman",
  מרוקו: "maˈʁoko",
  "אלג'יריה": "alˈd͡ʒiʁja",
  תוניסיה: "tuˈnisja",
  לוב: "luv",
  סודאן: "suˈdan",
  טורקיה: "ˈtuʁkja",
  קפריסין: "kafˈʁisin",
  רוסיה: "ˈʁusja",
  אוקראינה: "ukˈʁajna",
  פולין: "poˈlin",
  הונגריה: "hunˈɡaʁja",
  רומניה: "ʁoˈmanja",
  בולגריה: "bulˈɡaʁja",
  אוסטריה: "ˈostʁija",
  שווייץ: "ʃvajt͡s",
  הולנד: "ˈholand",
  בלגיה: "ˈbelɡja",
  שוודיה: "ˈʃvedja",
  נורווגיה: "noʁˈveɡja",
  דנמרק: "ˈdenemaʁk",
  פינלנד: "ˈfinland",
  יפן: "jaˈpan",
  קוריאה: "koˈʁeʔa",
  תאילנד: "ˈtajland",
  ברזיל: "bʁaˈzil",
  ארגנטינה: "aʁɡenˈtina",
  מקסיקו: "ˈmeksiko",
  קנדה: "ˈkanada",
  אילן: "iˈlan",
  גלעד: "ɡilˈʕad",
  נדב: "naˈdav",
  עידו: "iˈdo",
  ינאי: "jaˈnaj",
  דנה: "ˈdana",
  ענת: "aˈnat",
  רינה: "ʁiˈna",
  אורנה: "oʁˈna",
  דפנה: "dafˈna",
  נורית: "nuˈʁit",
  רונית: "ʁoˈnit",
  אורית: "oˈʁit",
  איריס: "iˈʁis",
  טל: "tal",
  מורן: "moˈʁan",
  שני: "ʃaˈni",
  לירון: "liˈʁon",
  קרן: "ˈkeʁen",
  ספיר: "saˈpiʁ",
  ענבר: "inˈbaʁ",
  קופמן: "ˈkofman",
  גרוסמן: "ˈɡʁosman",
  רוט: "ʁot",
  ברג: "beʁɡ",
  הורוביץ: "ˈhoʁovit͡s",
  ששון: "saˈson",
  דמארי: "daˈmaʁi",
  אשבל: "eʃˈbel",
  צוקרמן: "ˈt͡sukeʁman",
  זילברמן: "ˈzilbeʁman",
  מרקוס: "ˈmaʁkus",
  לנדאו: "ˈlandau",
  קפלן: "ˈkaplan",
  שפילמן: "ˈʃpilman",
  שטרן: "ʃteʁn",
  אפשטיין: "ˈepʃtejn",
  גולדנברג: "ˈɡoldenbeʁɡ",
  רובינשטיין: "ˈʁubinʃtejn",
  סגל: "ˈseɡal",
  לויט: "leˈvit",
  הלוי: "haleˈvi",
  "בן דוד": "ben daˈvid",
  "בן חיים": "ben χaˈjim",
  "בן ארי": "ben aˈʁi",
  "בר לב": "baʁ lev",
  "בר און": "baʁ on",
  טלמור: "talˈmoʁ",
  אלמגור: "almaˈɡoʁ",
  ארנון: "aʁˈnon",
  תלמה: "ˈtelma",
  "מאפיית אנג'ל": "maʔafiˈjat anˈd͡ʒel",
  נביעות: "neviˈʕot",
  "מי עדן": "mej ˈeden",
  יפאורה: "jafˈʔoʁa",
  תבורי: "tavoˈʁi",
  "טירת צבי": "tiˈʁat t͡svi",
  "עוף טוב": "of tov",
  "אדום אדום": "aˈdom aˈdom",
  חוגלה: "ˈχuɡla",
  קימברלי: "ˈkimbeʁli",
  ניקול: "niˈkol",
  פלדלת: "palˈdelet",
  מנורה: "menoˈʁa",
  "כלל ביטוח": "klal biˈtuʔaχ",
  ישיר: "jaˈʃiʁ",
  אמפא: "ˈampa",
  אמישראגז: "amiisʁaˈɡaz",
  פזגז: "pazˈɡaz",
  סופרגז: "ˈsupeʁɡaz",
  "בנק אגוד": "bank iˈɡud",
  "בנק יהב": "bank jaˈhav",
  יבואנים: "jevuʔaˈnim",
  "מכשירי תנועה": "maχʃiˈʁej tnuˈʕa",
  "קרסו מוטורס": "kaˈʁaso ˈmotoʁs",
  לובינסקי: "luˈbinski",
  "דלק מוטורס": "ˈdelek ˈmotoʁs",
  טלקאר: "talˈkaʁ",
  'סמל"ת': "samˈlat",
  "צ'מפיון מוטורס": "ˈt͡ʃempjon ˈmotoʁs",
  "יוניון מוטורס": "ˈjunjun ˈmotoʁs",
  תעבורה: "taʕavuˈʁa",
  גלים: "ɡaˈlim",
  "נתיב אקספרס": "naˈtiv eksˈpʁes",
  "דן בדרום": "dan badaˈʁom",
  אקסטרה: "ˈekstʁa",
  "אלקטרה אפיקים": "eˈlektʁa afiˈkim",
  כבלים: "kbaˈlim",
  "הוט מובייל": "hot moˈbjl",
  "גולן טלקום": "ɡoˈlan teleˈkom",
  אקספון: "eksˈpon",
  מרתון: "maʁaˈton",
  "רמי לוי תקשורת": "ˈʁami leˈvi tikˈʃoʁet",
  "טריפל סי": "tʁiˈpel si",
  "אינטרנט רימון": "inteʁnet ʁiˈmon",
  "בזק בינלאומי": "ˈbezek bejnleʔuˈmi",
  "ניו יורק": "nu joʁk",
  לונדון: "ˈlondon",
  פריז: "paˈʁiz",
  רומא: "ˈʁoma",
  מדריד: "madˈʁid",
  ברלין: "beʁˈlin",
  מוסקבה: "moskˈva",
  טוקיו: "ˈtokjo",
  "בייג'ינג": "bejˈd͡ʒinɡ",
  וושינגטון: "ˈvoʃinɡton",
  אמסטרדם: "ˈamsteʁdam",
  וינה: "ˈvina",
  פראג: "pʁaɡ",
  בודפשט: "budaˈpeʃt",
  אתונה: "aˈtuna",
  איסטנבול: "istanˈbul",
  דובאי: "duˈbaj",
  קהיר: "kaˈhiʁ",
  "רבת עמון": "ʁaˈbat aˈmon",
  דמשק: "daˈmesek",
  סידני: "ˈsidni",
  מלבורן: "ˈmelboʁn",
  טורונטו: "toˈʁonto",
  מונטריאול: "montʁiˈʔol",
  "לוס אנג'לס": "los ˈand͡ʒeles",
  שיקגו: "ʃiˈkaɡo",
  מיאמי: "maˈjami",
  בוסטון: "ˈboston",
  סיאטל: "siˈʔatel",
  "סן פרנסיסקו": "san fʁanˈsisko",
  סמסונג: "ˈsamsunɡ",
  סוני: "ˈsoni",
  פנסוניק: "panaˈsonik",
  טושיבה: "toˈʃiba",
  נינטנדו: "ninˈtendo",
  טויוטה: "toˈjota",
  הונדה: "ˈhonda",
  ניסאן: "niˈsan",
  מאזדה: "ˈmazda",
  סובארו: "suˈbaʁu",
  מיצובישי: "mit͡suˈbiʃi",
  יונדאי: "ˈjundaj",
  קיה: "ˈkija",
  מרצדס: "meʁˈt͡sedes",
  פורשה: "ˈpoʁʃe",
  אאודי: "ˈaudi",
  פולקסווגן: "ˈfolksvaɡen",
  פרארי: "feˈʁaʁi",
  למבורגיני: "lamboʁˈɡini",
  פיאט: "ˈfijat",
  רנו: "ʁeˈno",
  "פיג'ו": "piˈd͡ʒo",
  סיטרואן: "sitʁoˈʔen",
  שברולט: "ʃevʁoˈlet",
  פורד: "foʁd",
  טסלה: "ˈtesla",
  מקדונלדס: "mekˈdonalds",
  "בורגר קינג": "ˈbuʁɡeʁ kinɡ",
  "קוקה קולה": "ˈkoka ˈkola",
  פפסי: "ˈpepsi",
  ספרייט: "spʁajt",
  פנטה: "ˈfanta",
  אייפון: "ˈajfon",
  אייפד: "ˈajped",
  מקבוק: "ˈmakbuk",
  אנדרואיד: "ˈandʁoʔid",
  יוטיוב: "ˈjutjub",
  אינסטגרם: "ˈinstaɡʁam",
  טיקטוק: "ˈtiktok",
  וואטסאפ: "ˈvatsap",
  טלגרם: "ˈteleɡʁam",
  טוויטר: "ˈtviteʁ",
  לינקדאין: "ˈlinkdein",
  פינטרסט: "ˈpinteʁest",
  "סנאפצ'ט": "ˈsnapt͡ʃet",
  נטפליקס: "ˈnetfliks",
  דיסני: "ˈdisni",
  מארוול: "ˈmaʁvel",
  לגו: "ˈleɡo",
  נייקי: "ˈnajki",
  אדידס: "aˈdidas",
  פומה: "ˈpuma",
  ריבוק: "ˈʁibok",
  זארה: "ˈzaʁa",
  אמיר: "aˈmiʁ",
  שחר: "ˈʃaχaʁ",
  עילאי: "iˈlaj",
  שגיא: "saˈɡi",
  דקל: "ˈdekel",
  לוטם: "ˈlotem",
  רותם: "ˈʁotem",
  דורון: "doˈʁon",
  יוני: "ˈjoni",
  דני: "ˈdani",
  מוטי: "ˈmoti",
  יוסי: "ˈjosi",
  גלית: "ɡaˈlit",
  רווית: "ʁeˈvit",
  שרית: "saˈʁit",
  דורית: "doˈʁit",
  עידית: "iˈdit",
  לילך: "liˈlaχ",
  רקפת: "ʁaˈkefet",
  יסמין: "jasˈmin",
  סמדר: "smaˈdaʁ",
  אלונה: "aˈlona",
  איילת: "aˈjelet",
  הדס: "haˈdas",
  נטע: "ˈneta",
  נוגה: "ˈnoɡa",
  רעות: "ʁeˈʕut",
  מוריה: "moʁiˈja",
  ליאת: "liˈʔat",
  אביה: "aviˈja",
  אלמוג: "alˈmoɡ",
  אפיק: "aˈfik",
  אשחר: "eʃˈχaʁ",
  גיורא: "ɡiˈjoʁa",
  גפן: "ˈɡefen",
  דביר: "dviʁ",
  זיו: "ziv",
  יאיר: "jaˈʔiʁ",
  יגאל: "jiɡˈʔal",
  יהל: "jaˈhel",
  יואב: "joˈʔav",
  יותם: "joˈtam",
  כפיר: "kfiʁ",
  מנור: "maˈnoʁ",
  מעוז: "maˈʕoz",
  נאור: "naˈʔoʁ",
  ניצן: "niˈt͡san",
  סער: "ˈsaʕaʁ",
  עדו: "iˈdo",
  עוז: "oz",
  עילם: "ejˈlam",
  ערן: "eˈʁan",
  צחי: "ˈt͡saχi",
};

export const charMap: Record<string, string> = {
  א: "ʔ",
  ב: "v",
  ג: "ɡ",
  ד: "d",
  ה: "h",
  ו: "o",
  ז: "z",
  ח: "χ",
  ט: "t",
  י: "i",
  כ: "χ",
  ך: "χ",
  ל: "l",
  מ: "m",
  ם: "m",
  נ: "n",
  ן: "n",
  ס: "s",
  ע: "ʕ",
  פ: "f",
  ף: "f",
  צ: "t͡s",
  ץ: "t͡s",
  ק: "k",
  ר: "ʁ",
  ש: "ʃ",
  ת: "t",
};
