export const idMsRules = `
::NFC;

[iI] t { as } [:^Letter:] > i;
[iI] T { AS } [:^Letter:] > I;
[iI] t { AS } [:^Letter:] > I;
[iI] T { as } [:^Letter:] > i;
[mM] ekani { s } [:^Letter:] > k;
[mM] EKANI { S } [:^Letter:] > K;
[tT] ekni { s } [:^Letter:] > k;
[tT] EKNI { S } [:^Letter:] > K;
[aA] kademi { s } [:^Letter:] > k;
[aA] KADEMI { S } [:^Letter:] > K;
[pP] oliti { s } [:^Letter:] > k;
[pP] OLITI { S } [:^Letter:] > K;

::Null;

[:^Letter:] [kK] { are } [nN] [aA] > era;
[:^Letter:] [kK] { ARE } NA > ERA;
[:^Letter:] { y } [aA] [iI] [tT] [uU] > i;
[:^Letter:] { Y } [aA] [iI] [tT] [uU] > I;
[:^Letter:] { Y } AITU > I;
p } [iI] [kK] [iI] [rR] > f;
P } [iI] [kK] [iI] [rR] > F;
P } IKIR > F;
p } [aA] [hH] [aA] [mM] > f;
P } [aA] [hH] [aA] [mM] > F;
P } AHAM > F;
[nN] [aA] { p } [aA] [sS] > f;
NA { P } AS > F;
[bB] [eE] [rR] [bB] [eE] { d } [aA] [:^Letter:] > z;
BERBE { D } A [:^Letter:] > Z;
[pP] [eE] [rR] [bB] [eE] { d } [aA] [aA] [nN] > z;
PERBE { D } AAN > Z;
[mM] [eE] [mM] [bB] [eE] { d } [aA] [kK] [aA] [nN] > z;
MEMBE { D } AKAN > Z;
[bB] [eE] { d } [aA] [:^Letter:] > z;
BE { D } A [:^Letter:] > Z;
[jJ] [aA] [dD] { w } [aA] [lL] > u;
JAD { W } AL > U;
[:^Letter:] { u } [aA] [nN] [gG] > w;
[:^Letter:] { U } [aA] [nN] [gG] > W;
[:^Letter:] { U } ANG > W;
[:^Letter:] [kK] [eE] { u } [aA] [nN] [gG] [aA] [nN] > w;
[:^Letter:] KE { U } ANGAN > W;
sy } [aA] [rR] [aA] [fF] > s;
Sy } [aA] [rR] [aA] [fF] > S;
SY } ARAF > S;
[tT] [eE] [lL] [eE] { p } [oO] [nN] > f;
TELE { P } ON > F;
[tT] [eE] [lL] { p } [oO] [nN] > ef;
TEL { P } ON > EF;
[rR] { e } [sS] [iI] [kK] [oO] > i;
R { E } SIKO > I;
[:^Letter:] [eE] [sS] { a } [iI] [:^Letter:] > e;
[:^Letter:] ES { A } I [:^Letter:] > E;
[:^Letter:] [aA] r { sip } [:^Letter:] > kib;
[:^Letter:] [aA] R { SIP } [:^Letter:] > KIB;
[:^Letter:] [mM] u { s } ik [:^Letter:] > z;
[:^Letter:] [mM] U { S } IK [:^Letter:] > Z;
[:^Letter:] { kamar } ' ' [mM]andi > bilik;
[:^Letter:] { Kamar } ' ' [mM]andi > Bilik;
[:^Letter:] { KAMAR } ' ' MANDI > BILIK;
[:^Letter:] { kamar } ' ' [tT]idur > bilik;
[:^Letter:] { Kamar } ' ' [tT]idur > Bilik;
[:^Letter:] { KAMAR } ' ' TIDUR > BILIK;
[:^Letter:] { kantor } ' ' [pP]os > pejabat;
[:^Letter:] { Kantor } ' ' [pP]os > Pejabat;
[:^Letter:] { KANTOR } ' ' POS > PEJABAT;
[:^Letter:] { Maret } [:^Letter:] > Mac;
[:^Letter:] { maret } [:^Letter:] > mac;
[:^Letter:] { MARET } [:^Letter:] > MAC;
[:^Letter:] { Juni } [:^Letter:] > Jun;
[:^Letter:] { juni } [:^Letter:] > jun;
[:^Letter:] { JUNI } [:^Letter:] > JUN;
[:^Letter:] { Juli } [:^Letter:] > Julai;
[:^Letter:] { juli } [:^Letter:] > julai;
[:^Letter:] { JULI } [:^Letter:] > JULAI;
[:^Letter:] { Agustus } [:^Letter:] > Ogos;
[:^Letter:] { agustus } [:^Letter:] > ogos;
[:^Letter:] { AGUSTUS } [:^Letter:] > OGOS;
[:^Letter:] { Desember } [:^Letter:] > Disember;
[:^Letter:] { desember } [:^Letter:] > disember;
[:^Letter:] { DESEMBER } [:^Letter:] > DISEMBER;
[:^Letter:] { Senin } [:^Letter:] > Isnin;
[:^Letter:] { senin } [:^Letter:] > isnin;
[:^Letter:] { SENIN } [:^Letter:] > ISNIN;
[:^Letter:] { Kamis } [:^Letter:] > Khamis;
[:^Letter:] { kamis } [:^Letter:] > khamis;
[:^Letter:] { KAMIS } [:^Letter:] > KHAMIS;
[:^Letter:] { Jumat } [:^Letter:] > Jumaat;
[:^Letter:] { jumat } [:^Letter:] > jumaat;
[:^Letter:] { JUMAT } [:^Letter:] > JUMAAT;
[:^Letter:] { Arti } [:^Letter:] > Erti;
[:^Letter:] { arti } [:^Letter:] > erti;
[:^Letter:] { ARTI } [:^Letter:] > ERTI;
[:^Letter:] { Berarti } [:^Letter:] > Bererti;
[:^Letter:] { berarti } [:^Letter:] > bererti;
[:^Letter:] { BERARTI } [:^Letter:] > BERERTI;
[:^Letter:] { Stasiun } [:^Letter:] > Stesen;
[:^Letter:] { stasiun } [:^Letter:] > stesen;
[:^Letter:] { STASIUN } [:^Letter:] > STESEN;

::Null;

[:^Letter:] [bB] { u } [sS] [:^Letter:] > a;
[:^Letter:] B { U } S [:^Letter:] > A;
`;
