export const ipaZhRules = `
::Null;
::NFC;

[ː ˑ ˈ ʼ ˌ ꜜ ꜛ ˞ ̆ ̪ ̯ ‖ | ↗ ↘ \u0361 \u035C \u0329 \u0307 ʰ ʱ ˤ ̥ ̊ ̝ ʷ ˠ ˥ ˧ ˩ ̟] > ;

::Null;

$boundary = [:^Letter:];
$any_vowel = [a æ ʌ ɑ ɛ e i ɪ o ɒ ɔ u ʊ y ø œ ɵ ə ɜ ɚ ɝ ɨ ʲ ɤ ʉ ɐ â ă ê ô ơ ɘ {aɪ} {aʊ} {ɑɪ} {ɑʊ} {eɪ} {oʊ} {əʊ}];
$v_a = [a æ ʌ ɑ ɐ â ă {ɑː}];
$v_e = [ɛ e ɤ ê {eɪ}];
$v_er = [ɜ ə ø œ ɵ ɝ ơ ɘ {ɜ˞} {ɚ}];
$v_o = [o ɒ ɔ ô {ɔː} {oʊ} {əʊ}];
$v_i = [i ɪ ɨ {iː}];
$v_u = [u ʊ ʉ {uː} y];
$v_ju = [{ju} {juː} {jʊ}];
$v_ai = [{aɪ} {ɑɪ}];
$v_au = [{aʊ} {ɑʊ}];
$v_an1_v = [æ ʌ a ɐ ã];
$v_ang_vn = [ɑ ɔ ɒ ɐ ã a];
$v_en_v = [ɛ ɜ ə e ɛ̃ ẽ ɤ];
$v_ing = [ɪ i ĩ ɨ];
$v_un_v = [u ʊ ʉ ũ {uː}];
$c_z = [z {dz} {d͡z}];
$c_ts = [{ts} {t͡s}];
$c_s = [s θ];
$c_zh = [ʒ ʐ ʑ ž];
$c_sh = [ʃ ʂ ɕ];
$c_dzh = [{dʒ} {d͡ʒ} {dʐ} {d͡ʐ} {dʑ} {d͡ʑ} ɟ ʄ];
$c_tch = [{tʃ} {t͡ʃ} {tʂ} {t͡ʂ} {tɕ} {t͡ɕ} c č];

ʲ } [^$any_vowel] > ;
ɑ̃ > ɑŋ;
ɛ̃ > æn;
œ̃ > œŋ;
ɔ̃ > ɔŋ;
ã > an;
[ẽ ę] > ɛn;
ĩ > in;
õ > oŋ;
ũ > un;
[a ɑ] j } [^$any_vowel j w] > aɪ;
[o ɔ] j } [^$any_vowel j w] > oʊ;
[e ɛ] j } [^$any_vowel j w] > eɪ;
[a ɑ] j } $boundary > aɪ;
[o ɔ] j } $boundary > oʊ;
[e ɛ] j } $boundary > eɪ;
dʑ > dʒ;
tɕ > tʃ;
ɕ > ʃ;
ʑ > ʒ;
ɧ > ʃ;
dʐ > dʒ;
tʂ > tʃ;
ʂ > ʃ;
ʐ > ʒ;
r̝ > r;
ʏ > y;
ʉ > u;
ɫ > l;
[ɹ ɾ ʁ ʀ {r̩}] > r;
[ɡ ɠ ɣ ɢ] > g;
[x ħ ʜ ʢ] > h;
q > k;
ɗ > d;
ɓ > b;
ʈ > t;
ɖ > d;
ʋ > v;
ď > d;
ť > t;
ɭ > l;
ɽ > r;
ɥ > w;
ư > ɯ;
m } [bp] > n;
$any_vowel { ɲ > n;

::Null;

[ɑ æ] n > 兰;
o ɣ ɫ u > 奥卢;
g ɑ j ɯ t > 盖特;
g ɯ z ɯ > 克兹;
v ɑ n > 万;
v ɑ > 娃;
o f > 夫;
e n > 恩;
$any_vowel { r } [^$any_vowel j w] > 尔;
$any_vowel { r } $boundary > 尔;
[ɑ æ e] j > 艾;
[o œ] j > 欧;
$c_dzh œ j > 盖;
$c_tch ɑ j > 查伊;
g æ n dʒ æ > 甘贾;
$c_dzh œ > 盖;
$c_dzh æ > 盖;
χ ɑ n > 汉;
c æ n > 肯;
c æ > 科;
c i > 基;
b ɑ > 巴;
m ɯ > 姆;
l ɯ ɣ > 勒;
l ɯ > 勒;
n ɯ > 讷;
s ɯ > 瑟;
k ɯ > 库;
χ ɯ > 希;
$c_tch ɯ > 切;
$c_tch e > 切;
n ɑ > 纳;
l æ n > 连;
l æ > 连;
m i n $c_dzh æ > 明盖;
$boundary { $v_a n $v_a > 阿纳;
[v w] $v_a n $v_i > 万尼;
[v w] $v_a n [ɛ e] > 万内;
[v w] $v_a n } [^$any_vowel j w] > 万;
[v w] $v_a n } $boundary > 万;
$boundary { $v_a n > 安;
$v_a n } [^$any_vowel j w] > 兰;
[ɛ e] n } [^$any_vowel j w] > 恩;
$v_i j } $boundary > 维;
$v_i } [a ɛ ɔ u] > 亚;
jand > 燕德;
jɛks > 克斯;
jɛv > 耶夫;
n [j] [u ʊ {uː}] > 纽;
n {ju} > 纽;
l {ju} > 柳;
m {ju} > 缪;
j u > 尤;
j o > 约;
j a > 亚;
j ɛ > 耶;
j ɔ > 约;
i j ɛ > 耶;
ɛ } $boundary > 埃;
ɔ } $boundary > 欧;
$v_a t } b > 瓦特;
b $v_a n k > 邦克;
$boundary { $v_en_v n [$v_en_v $v_i] > 埃内;
$boundary { al > 阿尔;
$c_tch a r > 恰尔;
$c_tch ɛ n > 琴;
$c_tch $v_i > | 奇;
$c_tch } $v_i > 契;
$v_i { $c_tch > | 奇;
$c_tch } [n i] > 奇;
[伊 比 迪 菲 基 希 吉 利 米 尼 匹 瑞 锡 蒂 维 齐] { $c_tch > 奇;
nʲikoɫaj > 尼古拉;
vɫadʲimʲir > 弗拉基米尔;
t͡ɕɛxov > 契诃夫;
t͡ɕɛ > 切;
t͡ɕaj > 柴;
t͡ɕi > 奇;
t͡ɕo > 乔;
t͡ɕu > 丘;
d͡ʑ } i > 济;
$c_ts ɛ > 采;
$c_tch ɛ > 切;
$c_tch i > 奇;
t͡ɕ } i > 季;
t͡ɕ a > 恰;
d͡ʑ a > 贾;
t͡ɕ > 奇;
ɕːɛ > 谢;
lʲin > 林;
bʲin > 宾;
mʲin > 敏;
nʲin > 宁;
dʲmʲi > 德米;
skaja > 斯卡娅;
r i ɦ } $boundary > 里赫;
[^$any_vowel] { n $boundary > 恩;
ʒan > 占;
vanɔ > 万诺;
tanɔ > 塔诺;
vʲinːɪ > 维尼;
dan > 丹;
tan > 坦;
tʰaɲ > 坦;
nan > 南;
an > 兰;
ɛn > 恩;
on > 翁;
ɔn > 邦;
un > 温;
[hɦ] $v_a n > 汉;
[hɦ] $v_a > 哈;
[hɦ] $v_o n > 贡;
[hɦ] $v_o > 霍;
[hɦ] e > 赫;
ovʲit͡ɕ > 诺维奇;
evʲit͡ɕ > 耶维奇;
ij$ > ;
dʲjɛks > 德克斯;
va$ > 娃;
aja$ > 娅;
vna$ > 夫娜;
mʲir$ > 米尔;
vʲit͡ɕ > 维奇;
it͡ɕ > 奇;
skʲij > 斯基;
ski > 斯基;
sʲi > 西;
dʲi > 季;
vʲi > 维;
mʲi > 米;
tʲi > 季;
rʲi > 里;
lʲi > 里;
[r ɾ] [i ɪ] > 里;
nʲi > 尼;
sʲɛ > 谢;
vʲɛ > 韦;
dʲɛ > 杰;
tʲɛ > 捷;
rʲɛ > 列;
lʲɛ > 列;
nʲɛ > 涅;
mʲɛ > 梅;
pʲɛ > 佩;
fʲɛ > 费;
bʲɛ > 别;
gʲɛj > 盖;
gʲɛ > 格;
kʲɛ > 克;
xʲɛ > 赫;
burk > 堡;
kʲin > 金;
in > 因;
lʲjɛ > 列;
ov > 夫;
va > 瓦;
wa > 娃;
na > 娜;
ɕː > 希;
aj > 艾;
oj > 奥;
ij > 伊;
uj > 乌伊;
ʲa > 亚;
ʲɛ > 耶;
ʲi > 伊;
ʲo > 约;
ʲu > 尤;
ʂ > 什;
ʐ > 日;
lo > 洛;
lu > 卢;
b [ʲ j] a > 比亚;
p [ʲ j] a > 皮亚;
d [ʲ j] a > 佳;
t [ʲ j] a > 佳;
g [ʲ j] a > 吉亚;
k [ʲ j] a > 基亚;
v [ʲ j] a > 维亚;
f [ʲ j] a > 菲亚;
m [ʲ j] a > 米亚;
n [ʲ j] a > 尼亚;
l [ʲ j] a > 利亚;
r [ʲ j] a > 里亚;
l [ʲ j] > 利;
r [ʲ j] > 里;
b [ʲ j] > 比;
p [ʲ j] > 皮;
d [ʲ j] > 迪;
t [ʲ j] > 蒂;
g [ʲ j] > 吉;
k [ʲ j] > 基;
v [ʲ j] > 维;
f [ʲ j] > 菲;
m [ʲ j] > 米;
n [ʲ j] > 尼;
l j ə n > 廉;
l j [ə ʌ] > 利亚;
f i ə > 菲娅;
d ə n > 登;
z ə n > 逊;
m ə n > 曼;
[{ɡʷ}] > 格瓦;
[{kʷ}] > 库瓦;
[{hʷ}] > 霍瓦;
b [{oʊ} {əʊ}] > 博;
p [{oʊ} {əʊ}] > 坡;
d [{oʊ} {əʊ}] > 多;
t [{oʊ} {əʊ}] > 托;
f [{oʊ} {əʊ}] > 佛;
s [{oʊ} {əʊ}] > 索;
l [{oʊ} {əʊ}] > 罗;
r [{oʊ} {əʊ}] > 罗;
m [{oʊ} {əʊ}] > 莫;
[v w] [{oʊ} {əʊ}] > 沃;
$c_z [{oʊ} {əʊ}] > 佐;
$c_ts [{oʊ} {əʊ}] > 措;
$c_zh [{oʊ} {əʊ}] > 若;
$c_sh [{oʊ} {əʊ}] > 肖;
$c_dzh [{oʊ} {əʊ}] > 乔;
$c_tch [{oʊ} {əʊ}] > 乔;
h [{oʊ} {əʊ}] > 霍;
j [{oʊ} {əʊ}] > 约;
g [{oʊ} {əʊ}] > 哥;
k [{oʊ} {əʊ}] > 科;
n [{oʊ} {əʊ}] > 诺;
p r [u ʊ {uː}] > 普鲁;
b r [u ʊ {uː}] > 布鲁;
t r [u ʊ {uː}] > 特鲁;
d r [u ʊ {uː}] > 德鲁;
k r [u ʊ {uː}] > 克鲁;
g r [u ʊ {uː}] > 格鲁;
f r [u ʊ {uː}] > 弗鲁;
v r [u ʊ {uː}] > 弗鲁;
s r [u ʊ {uː}] > 斯鲁;
z r [u ʊ {uː}] > 兹鲁;
[ʃ ʒ] r [u ʊ {uː}] > 什鲁;
h r [u ʊ {uː}] > 赫鲁;
m r [u ʊ {uː}] > 姆鲁;
n r [u ʊ {uː}] > 努鲁;
r ə n > 伦;
r ə m > 姆;
b $v_o [m n ŋ] } [^$any_vowel j w] > 邦;
k $v_o [m n ŋ] } [^$any_vowel j w] > 孔;
l $v_o [m n ŋ] } [^$any_vowel j w] > 隆;
p $v_o [m n ŋ] } [^$any_vowel j w] > 蓬;
m $v_o [m n ŋ] } [^$any_vowel j w] > 蒙;
n $v_o [m n ŋ] } [^$any_vowel j w] > 农;
s $v_o [m n ŋ] } [^$any_vowel j w] > 松;
t $v_o [m n ŋ] } [^$any_vowel j w] > 通;
d $v_o [m n ŋ] } [^$any_vowel j w] > 东;
b $v_an1_v [m n ŋ] } [^$any_vowel j w] > 班;
p $v_an1_v [m n ŋ] } [^$any_vowel j w] > 潘;
d $v_an1_v [m n ŋ] } [^$any_vowel j w] > 丹;
t $v_an1_v [m n ŋ] } [^$any_vowel j w] > 坦;
g $v_an1_v [m n ŋ] } [^$any_vowel j w] > 甘;
k $v_an1_v [m n ŋ] } [^$any_vowel j w] > 坎;
v $v_an1_v [m n ŋ] } [^$any_vowel j w] > 万;
w $v_an1_v [m n ŋ] } [^$any_vowel j w] > 万;
f $v_an1_v [m n ŋ] } [^$any_vowel j w] > 凡;
$c_z $v_an1_v [m n ŋ] } [^$any_vowel j w] > 赞;
$c_ts $v_an1_v [m n ŋ] } [^$any_vowel j w] > 察;
$c_s $v_an1_v [m n ŋ] } [^$any_vowel j w] > 桑;
$c_sh $v_an1_v [m n ŋ] } [^$any_vowel j w] > 尚;
$c_dzh $v_an1_v [m n ŋ] } [^$any_vowel j w] > 詹;
$c_tch $v_an1_v [m n ŋ] } [^$any_vowel j w] > 钱;
h $v_an1_v [m n ŋ] } [^$any_vowel j w] > 汉;
m $v_an1_v [m n ŋ] } [^$any_vowel j w] > 曼;
n $v_an1_v [m n ŋ] } [^$any_vowel j w] > 南;
l $v_an1_v [m n ŋ] } [^$any_vowel j w] > 兰;
r $v_a [m n ŋ] } [^$any_vowel j w] > 兰;
r $v_an1_v [m n ŋ] } [^$any_vowel j w] > 伦;
j $v_an1_v [m n ŋ] } [^$any_vowel j w] > 扬;
$v_an1_v [m n ŋ] } [^$any_vowel j w] > 安;
b $v_ang_vn [m n ŋ] } [^$any_vowel j w] > 邦;
p $v_ang_vn [m n ŋ] } [^$any_vowel j w] > 庞;
d $v_ang_vn [m n ŋ] } [^$any_vowel j w] > 当;
t $v_ang_vn [m n ŋ] } [^$any_vowel j w] > 唐;
g $v_ang_vn [m n ŋ] } [^$any_vowel j w] > 冈;
k $v_ang_vn [m n ŋ] } [^$any_vowel j w] > 康;
v $v_ang_vn [m n ŋ] } [^$any_vowel j w] > 旺;
w $v_ang_vn [m n ŋ] } [^$any_vowel j w] > 旺;
f $v_ang_vn [m n ŋ] } [^$any_vowel j w] > 方;
$c_z $v_ang_vn [m n ŋ] } [^$any_vowel j w] > 藏;
$c_ts $v_ang_vn [m n ŋ] } [^$any_vowel j w] > 仓;
$c_s $v_ang_vn [m n ŋ] } [^$any_vowel j w] > 桑;
$c_zh $v_ang_vn [m n ŋ] } [^$any_vowel j w] > 让;
$c_sh $v_ang_vn [m n ŋ] } [^$any_vowel j w] > 尚;
$c_dzh $v_ang_vn [m n ŋ] } [^$any_vowel j w] > 章;
$c_tch $v_ang_vn [m n ŋ] } [^$any_vowel j w] > 昌;
h $v_ang_vn [m n ŋ] } [^$any_vowel j w] > 杭;
m $v_ang_vn [m n ŋ] } [^$any_vowel j w] > 芒;
n $v_ang_vn [m n ŋ] } [^$any_vowel j w] > 南;
l $v_ang_vn [m n ŋ] } [^$any_vowel j w] > 朗;
r $v_ang_vn [m n ŋ] } [^$any_vowel j w] > 荣;
j $v_ang_vn [m n ŋ] } [^$any_vowel j w] > 扬;
$v_ang_vn [m n ŋ] } [^$any_vowel j w] > 昂;
b [$v_en_v $v_un_v] n } [^$any_vowel j w] > 本;
p [$v_en_v $v_un_v] n } [^$any_vowel j w] > 彭;
d [$v_en_v $v_un_v] n } [^$any_vowel j w] > 登;
t [$v_en_v $v_un_v] n } [^$any_vowel j w] > 滕;
g [$v_en_v $v_un_v] n } [^$any_vowel j w] > 根;
k [$v_en_v $v_un_v] n } [^$any_vowel j w] > 肯;
v [$v_en_v $v_un_v] n } [^$any_vowel j w] > 文;
w [$v_en_v $v_un_v] n } [^$any_vowel j w] > 文;
f [$v_en_v $v_un_v] n } [^$any_vowel j w] > 芬;
$c_z [$v_en_v $v_un_v] n } [^$any_vowel j w] > 曾;
$c_ts [$v_en_v $v_un_v] n } [^$any_vowel j w] > 岑;
$c_s [$v_en_v $v_un_v] n } [^$any_vowel j w] > 森;
$c_zh [$v_en_v $v_un_v] n } [^$any_vowel j w] > 任;
$c_sh [$v_en_v $v_un_v] n } [^$any_vowel j w] > 申;
$c_dzh [$v_en_v $v_un_v] n } [^$any_vowel j w] > 真;
$c_tch [$v_en_v $v_un_v] n } [^$any_vowel j w] > 琴;
h [$v_en_v $v_un_v] n } [^$any_vowel j w] > 亨;
m [$v_en_v $v_un_v] n } [^$any_vowel j w] > 门;
n [$v_en_v $v_un_v] n } [^$any_vowel j w] > 嫩;
l [$v_en_v $v_un_v] n } [^$any_vowel j w] > 伦;
r [$v_en_v $v_un_v] n } [^$any_vowel j w] > 伦;
j $v_un_v n } [^$any_vowel j w] > 延;
j $v_en_v n } [^$any_vowel j w] > 延;
$v_en_v n } [^$any_vowel j w] > 恩;
$v_un_v n } [^$any_vowel j w] > 温;
b [$v_i $v_ing] [m n ŋ] } [^$any_vowel j w] > 宾;
p [$v_i $v_ing] [m n ŋ] } [^$any_vowel j w] > 平;
d [$v_i $v_ing] [m n ŋ] } [^$any_vowel j w] > 丁;
t [$v_i $v_ing] [m n ŋ] } [^$any_vowel j w] > 廷;
g [$v_i $v_ing] [m n ŋ] } [^$any_vowel j w] > 金;
k [$v_i $v_ing] [m n ŋ] } [^$any_vowel j w] > 金;
v [$v_i $v_ing] [m n ŋ] } [^$any_vowel j w] > 文;
w [$v_i $v_ing] [m n ŋ] } [^$any_vowel j w] > 温;
f [$v_i $v_ing] [m n ŋ] } [^$any_vowel j w] > 芬;
$c_z [$v_i $v_ing] [m n ŋ] } [^$any_vowel j w] > 津;
$c_ts [$v_i $v_ing] [m n ŋ] } [^$any_vowel j w] > 钦;
$c_s [$v_i $v_ing] [m n ŋ] } [^$any_vowel j w] > 辛;
$c_zh [$v_i $v_ing] [m n ŋ] } [^$any_vowel j w] > 任;
$c_sh [$v_i $v_ing] [m n ŋ] } [^$any_vowel j w] > 欣;
$c_dzh [$v_i $v_ing] [m n ŋ] } [^$any_vowel j w] > 金;
$c_tch [$v_i $v_ing] [m n ŋ] } [^$any_vowel j w] > 钦;
h [$v_i $v_ing] [m n ŋ] } [^$any_vowel j w] > 欣;
m [$v_i $v_ing] [m n ŋ] } [^$any_vowel j w] > 明;
n [$v_i $v_ing] [m n ŋ] } [^$any_vowel j w] > 宁;
l [$v_i $v_ing] [m n ŋ] } [^$any_vowel j w] > 林;
r [$v_i $v_ing] [m n ŋ] } [^$any_vowel j w] > 琳;
j [$v_i $v_ing] [m n ŋ] } [^$any_vowel j w] > 因;
$v_i [m n ŋ] } [^$any_vowel j w] > 因;
$v_ing [m n ŋ] } [^$any_vowel j w] > 英;
b $v_ai > 拜;
p $v_ai > 派;
d $v_ai > 代;
t $v_ai > 泰;
g $v_ai > 盖;
k $v_ai > 凯;
v $v_ai > 韦;
w $v_ai > 怀;
f $v_ai > 法;
$c_z $v_ai > 宰;
$c_ts $v_ai > 蔡;
$c_s $v_ai > 赛;
$c_sh $v_ai > 夏;
$c_dzh $v_ai > 贾;
$c_tch $v_ai > 柴;
h $v_ai > 海;
m $v_ai > 迈;
n $v_ai > 奈;
l $v_ai > 莱;
r $v_ai > 赖;
j $v_ai > 耶;
b $v_au > 鲍;
p $v_au > 保;
d $v_au > 道;
t $v_au > 陶;
g $v_au > 高;
k $v_au > 考;
v $v_au > 沃;
w $v_au > 沃;
f $v_au > 福;
$c_z $v_au > 藻;
$c_ts $v_au > 曹;
$c_s $v_au > 绍;
$c_sh $v_au > 绍;
$c_dzh $v_au > 焦;
$c_tch $v_au > 乔;
h $v_au > 豪;
m $v_au > 毛;
n $v_au > 瑙;
l $v_au > 劳;
r $v_au > 劳;
j $v_au > 尧;
b $v_ju > 比尤;
p $v_ju > 皮尤;
d $v_ju > 迪尤;
t $v_ju > 蒂尤;
g $v_ju > 久;
k $v_ju > 丘;
v $v_ju > 维尤;
w $v_ju > 威尤;
f $v_ju > 菲尤;
$c_z $v_ju > 久;
$c_ts $v_ju > 丘;
$c_s $v_ju > 休;
$c_sh $v_ju > 休;
$c_dzh $v_ju > 久;
$c_tch $v_ju > 丘;
h $v_ju > 休;
m $v_ju > 缪;
n $v_ju > 纽;
l $v_ju > 柳;
r $v_ju > 留;
β $v_a > 瓦;
β $v_e > 韦;
β $v_i > 维;
β $v_o > 沃;
β $v_u > 武;
b $v_a > 巴;
p $v_a > 帕;
ð $v_a > 达;
ð $v_e > 德;
ð $v_i > 迪;
ð $v_o > 多;
ð $v_u > 杜;
d $v_a > 达;
t $v_a > 塔;
g $v_a > 加;
k $v_a > 卡;
v $v_a > 瓦;
w $v_a > 瓦;
f $v_a > 法;
$c_z $v_a > 扎;
$c_ts $v_a > 察;
$c_s $v_a > 萨;
$c_zh $v_a > 扎;
$c_sh $v_a > 沙;
$c_dzh $v_a > 贾;
$c_tch $v_a > 查;
h $v_a > 哈;
m $v_a > 马;
n $v_a > 纳;
l $v_a > 拉;
r $v_a > 拉;
j $v_a > 亚;
b $v_e > 贝;
p $v_e > 佩;
d $v_e > 德;
t $v_e > 特;
g $v_e > 盖;
k $v_e > 凯;
v $v_e > 韦;
w $v_e > 韦;
f $v_e > 费;
$c_z $v_e > 泽;
$c_ts $v_e > 策;
$c_s $v_e > 塞;
$c_zh $v_e > 热;
$c_sh $v_e > 谢;
$c_dzh $v_e > 杰;
$c_tch $v_e > 切;
h $v_e > 赫;
m $v_e > 梅;
n æ f t > 内夫特;
n $v_e > 内;
l $v_e > 莱;
r $v_e > 雷;
j $v_e > 耶;
b $v_er > 伯;
p $v_er > 珀;
d $v_er > 德;
t $v_er > 特;
g $v_er > 格;
k $v_er > 克;
v $v_er > 弗;
w $v_er > 沃;
f $v_er > 弗;
$c_z $v_er > 泽;
$c_ts $v_er > 策;
$c_s $v_er > 瑟;
$c_zh $v_er > 热;
$c_sh $v_er > 舍;
$c_dzh $v_er > 哲;
$c_tch $v_er > 彻;
h $v_er > 赫;
m $v_er > 默;
n $v_er > 纳;
l $v_er > 勒;
j $v_er > 耶;
b $v_i > 比;
p $v_i > 皮;
d $v_i > 迪;
t $v_i > 蒂;
g $v_i > 吉;
k $v_i > 基;
v $v_i > 维;
w $v_i > 威;
f $v_i > 菲;
$c_z $v_i > 齐;
$c_ts $v_i > 齐;
$c_ts } $v_i > 齐;
$c_ts } [a ɛ ɔ u] > 茨;
$c_s $v_i > 西;
$c_zh $v_i > 日;
$c_sh $v_i > 希;
$c_dzh $v_i > 吉;
h $v_i > 希;
m $v_i > 米;
n $v_i > 尼;
l $v_i > 利;
r $v_i > 瑞;
j $v_i > 伊;
b $v_o > 博;
p $v_o > 波;
d $v_o > 多;
t $v_o > 托;
g $v_o > 戈;
k $v_o > 科;
v $v_o > 沃;
w $v_o > 沃;
f $v_o > 福;
$c_z $v_o > 佐;
$c_ts $v_o > 措;
$c_s $v_o > 索;
$c_zh $v_o > 若;
$c_sh $v_o > 肖;
$c_dzh $v_o > 乔;
$c_tch $v_o > 乔;
h $v_o > 霍;
m $v_o > 莫;
n $v_o > 诺;
l $v_o > 洛;
r $v_o > 罗;
j $v_o > 约;
b $v_u > 布;
p $v_u > 普;
d $v_u > 杜;
t $v_u > 图;
g $v_u > 古;
k $v_u > 库;
v $v_u > 武;
w $v_u > 伍;
f $v_u > 富;
$c_z $v_u > 祖;
$c_ts $v_u > 楚;
$c_s $v_u > 苏;
$c_zh $v_u > 茹;
$c_sh $v_u > 舒;
$c_dzh $v_u > 朱;
$c_tch $v_u > 楚;
h $v_u > 胡;
m $v_u > 穆;
n $v_u > 努;
l $v_u > 卢;
r $v_u > 鲁;
j $v_u > 尤;
$v_ai > 艾;
$v_au > 奥;
$v_ju > 尤;
$v_a > 阿;
$v_e > 埃;
$v_er > 厄;
$v_i > 伊;
{aɪ} > 艾;
{eɪ} > 埃;
{oʊ} > 欧;
{əʊ} > 欧;
$v_o > 奥;
$v_u > 乌;
r [ə ər ɚ] > 尔;
r $v_er > 勒;
ɚ > 尔;
{ɜ˞} > 尔;
ə > 厄;
[ʃ ʒ] ə n > 申;
tʃən > 琴;
dʒən > 震;
f } [^$any_vowel j w] > 弗;
[v w] } [^$any_vowel] > 夫;
[v w f] } $boundary > 夫;
$c_dzh } i > 济;
$c_dzh } [a ɛ ɔ u] > 乔;
$c_dzh > 基;
$c_tch > 奇;
$c_ts > 茨;
d z > 兹;
$c_z > 兹;
b > 布;
p > 普;
d > 德;
t > 特;
g > 格;
a > 阿;
ɑ > 阿;
k > 克;
β > 夫;
v > 夫;
f > 夫;
ð > 德;
θ > 斯;
s > 斯;
z > 兹;
ʃ > 什;
ʒ > 日;
m > 姆;
l > 尔;
r > 尔;
n > 恩;
j > 伊;
ɪ > 伊;
w > 沃;
ŋ > 恩;
ɝ > 尔;
e > 埃;
y > 郁;
ø > 厄;
œ > 厄;
ç > 希;
ɲ a > 尼亚;
ɲ i > 尼;
ɲ > 尼;
ʁ > 尔;
ʀ > 尔;
ʎ i > 利;
ʎ > 利;
ɨ > 依;
ʲ > 亚;
ɕ > 什;
ɤ > 厄;
[ʔ ʕ] } $any_vowel > ;
ʕ > 阿; 
ʔ > 阿;
ʈʰ > 特;
ʈ > 特;
ɖʱ > 德;
ɖ > 德;
ɳ > 尼;
þ > 斯;
ɓ > 布;
ɗ > 德;
ɠ > 格;
ɬ > 利;
[ɱ ɴ] > 姆;
ɦ > 格;
h > 赫;
[ʂ ʐ] > 什;
ɯ > 库;
χ > 希;
ɣ > 赫;
æ > 亚;
i > 伊;
ɐ > 厄;
ʝ > 耶;

::Null;

[ ̃] > ;
`;
