export const ipaZhRules = `
  $v_a = [a æ ʌ ɑ {ɑː}];
  $v_e = [ɛ {eɪ}];
  $v_er = [ɜ ə {ɜ˞} {ɚ}];
  $v_i = [i ɪ {iː}];
  $v_o = [o ɒ ɔ {ɔː} {oʊ} {əʊ}];
  $v_u = [u ʊ {uː}];
  $v_ju = [{ju} {juː} {jʊ}];
  $v_ai = [{aɪ}];
  $v_au = [{aʊ}];
  $v_an1_v = [æ ʌ a];
  $v_an1_ng = [æ];
  $v_ang_vn = [ɑ ɔ ɒ];
  $v_ang_aun = [{aʊ}];
  $v_ang_vng = [ʌ ɒ];
  $v_en_v = [ɛ ɜ ə];
  $v_en_ngv = [ɛ ə];
  $v_in_v = [ɪ i {iː}];
  $v_ing = [ɪ];
  $v_un_v = [u ʊ {uː}];
  $v_ung = [ʊ];
  $c_z = [z {dz}];
  $c_ts = [{ts}];
  $c_s = [s ð θ];
  $c_zh = [ʒ];
  $c_sh = [ʃ];
  $c_dzh = [{dʒ}];
  $c_tch = [{tʃ}];
  $c_gw = [{ɡʷ}];
  $c_kw = [{kʷ}];
  $c_hw = [{hʷ}];
  ˈ > ;
  ˌ > ;
  ˞ > ;
  ɹ > | r;
  ɡ > | g;
  m } [bp] > n;
  l j ə n > 廉;
  l j [ə ʌ] > 利亚;
  f i ə > 菲娅;
  d ə n > 登;
  z ə n > 逊;
  m ə n > 曼;
  b {oʊ} > 博;
  p {oʊ} > 坡;
  d {oʊ} > 多;
  t {oʊ} > 托;
  f {oʊ} > 佛;
  s {oʊ} > 索;
  l {oʊ} > 罗;
  r {oʊ} > 罗;
  m {oʊ} > 莫;
  n {oʊ} > 诺;
  v {oʊ} > 沃;
  w {oʊ} > 沃;
  $c_z {oʊ} > 佐;
  $c_ts {oʊ} > 措;
  $c_zh {oʊ} > 若;
  $c_sh {oʊ} > 肖;
  $c_dzh {oʊ} > 乔;
  $c_tch {oʊ} > 乔;
  h {oʊ} > 霍;
  j {oʊ} > 约;
  g [{oʊ} {əʊ}] > 哥;
  k [{oʊ} {əʊ}] > 科;
  b {əʊ} > 博;
  p {əʊ} > 坡;
  d {əʊ} > 多;
  t {əʊ} > 托;
  f {əʊ} > 佛;
  s {əʊ} > 索;
  l {əʊ} > 罗;
  r {əʊ} > 罗;
  m {əʊ} > 莫;
  n {əʊ} > 诺;
  v {əʊ} > 沃;
  w {əʊ} > 沃;
  $c_z {əʊ} > 佐;
  $c_ts {əʊ} > 措;
  $c_zh {əʊ} > 若;
  $c_sh {əʊ} > 肖;
  $c_dzh {əʊ} > 乔;
  $c_tch {əʊ} > 乔;
  h {əʊ} > 霍;
  j {əʊ} > 约;
  n [{oʊ} {əʊ}] > 诺;
  n [j] [u ʊ {uː}] > 纽;
  n {ju} > 纽;
  l {ju} > 柳;
  m {ju} > 缪;
  p r [u ʊ {uː}] > 普鲁;
  b r [u ʊ {uː}] > 布鲁;
  t r [u ʊ {uː}] > 特鲁;
  d r [u ʊ {uː}] > 德鲁;
  k r [u ʊ {uː}] > 克鲁;
  g r [u ʊ {uː}] > 格鲁;
  f r [u ʊ {uː}] > 弗鲁;
  v r [u ʊ {uː}] > 弗鲁;
  s r [u ʊ {uː}] > 斯鲁;
  z r [u ʊ {uː}] > 兹鲁;
  [ʃ ʒ] r [u ʊ {uː}] > 什鲁;
  h r [u ʊ {uː}] > 赫鲁;
  m r [u ʊ {uː}] > 姆鲁;
  n r [u ʊ {uː}] > 努鲁;
  tr > 特尔;
  dr > 德尔;
  r ə n > 伦;
  r ə m > 姆;
  b $v_an1_v n > 班;
  p $v_an1_v n > 潘;
  d $v_an1_v n > 丹;
  t $v_an1_v n > 坦;
  g $v_an1_v n > 甘;
  k $v_an1_v n > 坎;
  v $v_an1_v n > 万;
  w $v_an1_v n > 万;
  f $v_an1_v n > 凡;
  $c_z $v_an1_v n > 赞;
  $c_ts $v_an1_v n > 灿;
  $c_s $v_an1_v n > 桑;
  $c_sh $v_an1_v n > 尚;
  $c_dzh $v_an1_v n > 詹;
  $c_tch $v_an1_v n > 钱;
  h $v_an1_v n > 汉;
  m $v_an1_v n > 曼;
  n $v_an1_v n > 南;
  l $v_an1_v n > 兰;
  r $v_an1_v n > 伦;
  j $v_an1_v n > 扬;
  $v_an1_v n > 安;
  b $v_an1_ng ŋ > 班;
  p $v_an1_ng ŋ > 潘;
  d $v_an1_ng ŋ > 丹;
  t $v_an1_ng ŋ > 坦;
  g $v_an1_ng ŋ > 甘;
  k $v_an1_ng ŋ > 坎;
  v $v_an1_ng ŋ > 万;
  w $v_an1_ng ŋ > 万;
  f $v_an1_ng ŋ > 凡;
  $c_z $v_an1_ng ŋ > 赞;
  $c_ts $v_an1_ng ŋ > 灿;
  $c_s $v_an1_ng ŋ > 桑;
  $c_sh $v_an1_ng ŋ > 尚;
  $c_dzh $v_an1_ng ŋ > 詹;
  $c_tch $v_an1_ng ŋ > 钱;
  h $v_an1_ng ŋ > 汉;
  m $v_an1_ng ŋ > 曼;
  n $v_an1_ng ŋ > 南;
  l $v_an1_ng ŋ > 兰;
  r $v_an1_ng ŋ > 伦;
  j $v_an1_ng ŋ > 扬;
  $v_an1_ng ŋ > 安;
  b $v_ang_vn n > 邦;
  p $v_ang_vn n > 庞;
  d $v_ang_vn n > 当;
  t $v_ang_vn n > 唐;
  g $v_ang_vn n > 冈;
  k $v_ang_vn n > 康;
  v $v_ang_vn n > 旺;
  w $v_ang_vn n > 旺;
  f $v_ang_vn n > 方;
  $c_z $v_ang_vn n > 藏;
  $c_ts $v_ang_vn n > 仓;
  $c_s $v_ang_vn n > 桑;
  $c_zh $v_ang_vn n > 让;
  $c_sh $v_ang_vn n > 尚;
  $c_dzh $v_ang_vn n > 章;
  $c_tch $v_ang_vn n > 昌;
  h $v_ang_vn n > 杭;
  m $v_ang_vn n > 芒;
  n $v_ang_vn n > 南;
  l $v_ang_vn n > 朗;
  r $v_ang_vn n > 荣;
  j $v_ang_vn n > 扬;
  $v_ang_vn n > 昂;
  b $v_ang_vng ŋ > 邦;
  p $v_ang_vng ŋ > 庞;
  d $v_ang_vng ŋ > 当;
  t $v_ang_vng ŋ > 唐;
  g $v_ang_vng ŋ > 冈;
  k $v_ang_vng ŋ > 康;
  v $v_ang_vng ŋ > 旺;
  w $v_ang_vng ŋ > 旺;
  f $v_ang_vng ŋ > 方;
  $c_z $v_ang_vng ŋ > 藏;
  $c_ts $v_ang_vng ŋ > 仓;
  $c_s $v_ang_vng ŋ > 桑;
  $c_zh $v_ang_vng ŋ > 让;
  $c_sh $v_ang_vng ŋ > 尚;
  $c_dzh $v_ang_vng ŋ > 章;
  $c_tch $v_ang_vng ŋ > 昌;
  h $v_ang_vng ŋ > 杭;
  m $v_ang_vng ŋ > 芒;
  n $v_ang_vng ŋ > 南;
  l $v_ang_vng ŋ > 朗;
  r $v_ang_vng ŋ > 荣;
  j $v_ang_vng ŋ > 扬;
  $v_ang_vng ŋ > 昂;
  b $v_en_v n > 本;
  p $v_en_v n > 彭;
  d $v_en_v n > 登;
  t $v_en_v n > 滕;
  g $v_en_v n > 根;
  k $v_en_v n > 肯;
  v $v_en_v n > 文;
  w $v_en_v n > 文;
  f $v_en_v n > 芬;
  $c_z $v_en_v n > 曾;
  $c_ts $v_en_v n > 岑;
  $c_s $v_en_v n > 森;
  $c_zh $v_en_v n > 任;
  $c_sh $v_en_v n > 申;
  $c_dzh $v_en_v n > 真;
  $c_tch $v_en_v n > 琴;
  h $v_en_v n > 亨;
  m $v_en_v n > 门;
  n $v_en_v n > 嫩;
  l $v_en_v n > 伦;
  r $v_en_v n > 伦;
  j $v_en_v n > 延;
  $v_en_v n > 恩;
  b $v_in_v n > 宾;
  p $v_in_v n > 平;
  d $v_in_v n > 丁;
  t $v_in_v n > 廷;
  g $v_in_v n > 金;
  k $v_in_v n > 金;
  v $v_in_v n > 文;
  w $v_in_v n > 温;
  f $v_in_v n > 芬;
  $c_z $v_in_v n > 津;
  $c_ts $v_in_v n > 钦;
  $c_s $v_in_v n > 辛;
  $c_zh $v_in_v n > 任;
  $c_sh $v_in_v n > 欣;
  $c_dzh $v_in_v n > 金;
  $c_tch $v_in_v n > 钦;
  h $v_in_v n > 欣;
  m $v_in_v n > 明;
  n $v_in_v n > 宁;
  l $v_in_v n > 林;
  r $v_in_v n > 琳;
  j $v_in_v n > 因;
  $v_in_v n > 因;
  b $v_ing ŋ > 宾;
  p $v_ing ŋ > 平;
  d $v_ing ŋ > 丁;
  t $v_ing ŋ > 廷;
  g $v_ing ŋ > 金;
  k $v_ing ŋ > 金;
  v $v_ing ŋ > 文;
  w $v_ing ŋ > 温;
  f $v_ing ŋ > 芬;
  $c_z $v_ing ŋ > 津;
  $c_ts $v_ing ŋ > 钦;
  $c_s $v_ing ŋ > 辛;
  $c_zh $v_ing ŋ > 任;
  $c_sh $v_ing ŋ > 欣;
  $c_dzh $v_ing ŋ > 金;
  $c_tch $v_ing ŋ > 钦;
  h $v_ing ŋ > 欣;
  m $v_ing ŋ > 明;
  n $v_ing ŋ > 宁;
  l $v_ing ŋ > 林;
  r $v_ing ŋ > 琳;
  j $v_ing ŋ > 因;
  $v_ing ŋ > 英;
  b $v_un_v n > 本;
  p $v_un_v n > 彭;
  d $v_un_v n > 登;
  t $v_un_v n > 滕;
  g $v_un_v n > 根;
  k $v_un_v n > 肯;
  v $v_un_v n > 文;
  w $v_un_v n > 文;
  f $v_un_v n > 芬;
  $c_z $v_un_v n > 曾;
  $c_ts $v_un_v n > 岑;
  $c_s $v_un_v n > 森;
  $c_zh $v_un_v n > 任;
  $c_sh $v_un_v n > 申;
  $c_dzh $v_un_v n > 真;
  $c_tch $v_un_v n > 琴;
  h $v_un_v n > 亨;
  m $v_un_v n > 门;
  n $v_un_v n > 嫩;
  l $v_un_v n > 伦;
  r $v_un_v n > 伦;
  j $v_un_v n > 延;
  $v_un_v n > 温;
  b $v_ung ŋ > 邦;
  p $v_ung ŋ > 庞;
  d $v_ung ŋ > 当;
  t $v_ung ŋ > 唐;
  g $v_ung ŋ > 冈;
  k $v_ung ŋ > 康;
  v $v_ung ŋ > 旺;
  w $v_ung ŋ > 旺;
  f $v_ung ŋ > 方;
  $c_z $v_ung ŋ > 藏;
  $c_ts $v_ung ŋ > 仓;
  $c_s $v_ung ŋ > 桑;
  $c_zh $v_ung ŋ > 让;
  $c_sh $v_ung ŋ > 尚;
  $c_dzh $v_ung ŋ > 章;
  $c_tch $v_ung ŋ > 昌;
  h $v_ung ŋ > 杭;
  m $v_ung ŋ > 芒;
  n $v_ung ŋ > 南;
  l $v_ung ŋ > 朗;
  r $v_ung ŋ > 荣;
  j $v_ung ŋ > 扬;
  $v_ung ŋ > 翁;
  b $v_ai > 拜;
  p $v_ai > 派;
  d $v_ai > 代;
  t $v_ai > 泰;
  g $v_ai > 盖;
  k $v_ai > 凯;
  v $v_ai > 韦;
  w $v_ai > 怀;
  f $v_ai > 法;
  $c_z $v_ai > 宰;
  $c_ts $v_ai > 蔡;
  $c_s $v_ai > 赛;
  $c_sh $v_ai > 夏;
  $c_dzh $v_ai > 贾;
  $c_tch $v_ai > 柴;
  h $v_ai > 海;
  m $v_ai > 迈;
  n $v_ai > 奈;
  l $v_ai > 莱;
  r $v_ai > 赖;
  j $v_ai > 耶;
  b $v_au > 鲍;
  p $v_au > 保;
  d $v_au > 道;
  t $v_au > 陶;
  g $v_au > 高;
  k $v_au > 考;
  v $v_au > 沃;
  w $v_au > 沃;
  f $v_au > 福;
  $c_z $v_au > 藻;
  $c_ts $v_au > 曹;
  $c_s $v_au > 绍;
  $c_sh $v_au > 绍;
  $c_dzh $v_au > 焦;
  $c_tch $v_au > 乔;
  h $v_au > 豪;
  m $v_au > 毛;
  n $v_au > 瑙;
  l $v_au > 劳;
  r $v_au > 劳;
  j $v_au > 尧;
  b $v_ju > 比尤;
  p $v_ju > 皮尤;
  d $v_ju > 迪尤;
  t $v_ju > 蒂尤;
  g $v_ju > 久;
  k $v_ju > 丘;
  v $v_ju > 维尤;
  w $v_ju > 威尤;
  f $v_ju > 菲尤;
  $c_z $v_ju > 久;
  $c_ts $v_ju > 丘;
  $c_s $v_ju > 休;
  $c_sh $v_ju > 休;
  $c_dzh $v_ju > 久;
  $c_tch $v_ju > 丘;
  h $v_ju > 休;
  m $v_ju > 缪;
  n $v_ju > 纽;
  l $v_ju > 柳;
  r $v_ju > 留;
  b $v_a > 巴;
  p $v_a > 帕;
  d $v_a > 达;
  t $v_a > 塔;
  g $v_a > 加;
  k $v_a > 卡;
  v $v_a > 瓦;
  w $v_a > 瓦;
  f $v_a > 法;
  $c_z $v_a > 扎;
  $c_ts $v_a > 察;
  $c_s $v_a > 萨;
  $c_zh $v_a > 扎;
  $c_sh $v_a > 沙;
  $c_dzh $v_a > 贾;
  $c_tch $v_a > 查;
  h $v_a > 哈;
  m $v_a > 马;
  n $v_a > 纳;
  l $v_a > 拉;
  r $v_a > 拉;
  j $v_a > 亚;
  b $v_e > 贝;
  p $v_e > 佩;
  d $v_e > 德;
  t $v_e > 特;
  g $v_e > 盖;
  k $v_e > 凯;
  v $v_e > 韦;
  w $v_e > 韦;
  f $v_e > 费;
  $c_z $v_e > 泽;
  $c_ts $v_e > 策;
  $c_s $v_e > 塞;
  $c_zh $v_e > 热;
  $c_sh $v_e > 谢;
  $c_dzh $v_e > 杰;
  $c_tch $v_e > 切;
  h $v_e > 赫;
  m $v_e > 梅;
  n $v_e > 内;
  l $v_e > 莱;
  r $v_e > 雷;
  j $v_e > 耶;
  b $v_er > 伯;
  p $v_er > 珀;
  d $v_er > 德;
  t $v_er > 特;
  g $v_er > 格;
  k $v_er > 克;
  v $v_er > 弗;
  w $v_er > 沃;
  f $v_er > 弗;
  $c_z $v_er > 泽;
  $c_ts $v_er > 策;
  $c_s $v_er > 瑟;
  $c_zh $v_er > 热;
  $c_sh $v_er > 舍;
  $c_dzh $v_er > 哲;
  $c_tch $v_er > 彻;
  h $v_er > 赫;
  m $v_er > 默;
  n $v_er > 纳;
  l $v_er > 勒;
  j $v_er > 耶;
  b $v_i > 比;
  p $v_i > 皮;
  d $v_i > 迪;
  t $v_i > 蒂;
  g $v_i > 吉;
  k $v_i > 基;
  v $v_i > 维;
  w $v_i > 威;
  f $v_i > 菲;
  $c_z $v_i > 齐;
  $c_ts $v_i > 齐;
  $c_s $v_i > 西;
  $c_zh $v_i > 日;
  $c_sh $v_i > 希;
  $c_dzh $v_i > 吉;
  $c_tch $v_i > 奇;
  h $v_i > 希;
  m $v_i > 米;
  n $v_i > 尼;
  l $v_i > 利;
  r $v_i > 瑞;
  j $v_i > 伊;
  b $v_o > 博;
  p $v_o > 波;
  d $v_o > 多;
  t $v_o > 托;
  g $v_o > 戈;
  k $v_o > 科;
  v $v_o > 沃;
  w $v_o > 沃;
  f $v_o > 福;
  $c_z $v_o > 佐;
  $c_ts $v_o > 措;
  $c_s $v_o > 索;
  $c_zh $v_o > 若;
  $c_sh $v_o > 肖;
  $c_dzh $v_o > 乔;
  $c_tch $v_o > 乔;
  h $v_o > 霍;
  m $v_o > 莫;
  n $v_o > 诺;
  l $v_o > 洛;
  r $v_o > 罗;
  j $v_o > 约;
  b $v_u > 布;
  p $v_u > 普;
  d $v_u > 杜;
  t $v_u > 图;
  g $v_u > 古;
  k $v_u > 库;
  v $v_u > 武;
  w $v_u > 伍;
  f $v_u > 富;
  $c_z $v_u > 祖;
  $c_ts $v_u > 楚;
  $c_s $v_u > 苏;
  $c_zh $v_u > 茹;
  $c_sh $v_u > 舒;
  $c_dzh $v_u > 朱;
  $c_tch $v_u > 楚;
  h $v_u > 胡;
  m $v_u > 穆;
  n $v_u > 努;
  l $v_u > 卢;
  r $v_u > 鲁;
  j $v_u > 尤;
  $v_ai > 艾;
  $v_au > 奥;
  $v_ju > 尤;
  $v_a > 阿;
  $v_e > 埃;
  $v_er > 厄;
  $v_i > 伊;
  $v_o > 奥;
  $v_u > 乌;
  {aɪ} > 艾;
  {aʊ} > 奥;
  {eɪ} > 埃;
  {oʊ} > 欧;
  {əʊ} > 欧;
  r [ə ər ɚ] > 尔;
  r $v_er > 勒;
  ɚ > 尔;
  {ɜ˞} > 尔;
  ə > 厄;
  [ʃ ʒ] ə n > 申;
  t ʃ ə n > 琴;
  d ʒ ə n > 震;
  b > 布;
  p > 普;
  d > 德;
  t > 特;
  g > 格;
  a > 阿;
  ɑ > 阿;
  k > 克;
  v > 夫;
  f > 夫;
  ð > 斯;
  θ > 斯;
  s > 斯;
  z > 兹;
  ʃ > 什;
  ʒ > 日;
  m > 姆;
  l > 尔;
  r > 尔;
  n > 恩;
  j > 伊;
  w > 沃;
  ŋ > 恩;
  ɾ > 塔;
  ɝ > 尔;
  e > 埃;
`;
