export const ipaJaRules = `
::Null;

[ˈˌˑʰʱʷˠˤʼ͜͡\\.\u0300-\u036F\u02E0-\u02E4\uA71B-\uA71F] > ;

::Null;

[- \t]+ > ・;

pː > pp;
bː > bb;
tː > tt;
dː > dd;
kː > kk;
gː > gg;
sː > ss;
zː > zz;
fː > ff;
vː > vv;
mː > mm;
nː > nn;
ɲː > nny;
lː > rr;
rː > rr;
ʃː > shsh;
ʒː > jj;

ã > an;
ɑ̃ > an;
ẽ > en;
ɛ̃ > en;
œ̃ > en;
ĩ > in;
õ > on;
ɔ̃ > on;
ũ > un;
[ɑɐʌɒæaəɚɝɜ] > a;
[ɪɨi] > i;
[yʏ] > yu;
[ʊɯʉɵu] > u;
[ɛœøɤe] > e;
[ɔo] > o;
[ɡɢg] > g;
[kq] > k;
c } [aɑɐʌɒæəɚɝɜyʏʊɯʉɵuɔoãɑ̃õɔ̃ũœ̃] > ky;
ɟ } [aɑɐʌɒæəɚɝɜyʏʊɯʉɵuɔoãɑ̃õɔ̃ũœ̃] > gy;
c > k;
ɟ > g;
dʒ > j;
dʑ > j;
dʐ > j;
dzh > j;
dz > z;
[dɖɗ] > d;
tʃ > ch;
tɕ > ch;
tʂ > ch;
[tʈṭ] > t;
[pɓ] > p;
[bβ] > b;
[mɱ] > m;
[nɳɴ] > n;
ɲ > ny;
ŋ } [ɑɐʌɒæaəɚɝɜɪɨiyʏʊɯʉɵuɛœøɤeɔo] > ng;
ŋ > n;
ʎ > ry;
[rʀɾɽɹɻlɫʟʁɭ] > r;
[fɸ] > f;
[vʋ] > v;
θ > s;
ð > z;
[ʃʂɕɧ] > sh;
[ʒʐʑ] > j;
ʲ > y;
j > y;
ʝ > y;
ɥ > y;
[xχħhɦ] > h;
ç > hy;
ɣ > g;
[ʕʔ] > ;
[wʍ] > w;
tsh > ch;
zh > j;

::Null;

yy > y;
ː > ー;

::Null;

m } p > ン;
m } b > ン;
m } m > ン;
m } f > ン;
m } v > ン;
k } k > ッ;
g } g > ッ;
s } s > ッ;
z } z > ッ;
j } j > ッ;
t } t > ッ;
d } d > ッ;
p } p > ッ;
b } b > ッ;
f } f > ッ;
v } v > ッ;
r } r > ッ;
t } ch > ッ;
sh } sh > ッ;
ch } ch > ッ;
n } n > ン;

kya > キャ; kyi > キィ; kyu > キュ; kye > キェ; kyo > キョ;
gya > ギャ; gyi > ギィ; gyu > ギュ; gye > ギェ; gyo > ギョ;
sha > シャ; shi > シ; shu > シュ; she > シェ; sho > ショ;
ja > ジャ; ji > ジ; ju > ジュ; je > ジェ; jo > ジョ;
cha > チャ; chi > チ; chu > チュ; che > チェ; cho > チョ;
tsa > ツァ; tsi > ツィ; tsu > ツ; tse > ツェ; tso > ツォ;
sya > シャ; syi > シィ; syu > シュ; sye > シェ; syo > ショ;
zya > ジャ; zyi > ジィ; zyu > ジュ; zye > ジェ; zyo > ジョ;
tya > チャ; tyi > チィ; tyu > チュ; tye > チェ; tyo > チョ;
dya > ヂャ; dyi > ヂィ; dyu > ヂュ; dye > ヂェ; dyo > ヂョ;
nya > ニャ; nyi > ニィ; nyu > ニュ; nye > ニェ; nyo > ニョ;
hya > ヒャ; hyi > ヒィ; hyu > ヒュ; hye > ヒェ; hyo > ヒョ;
mya > ミャ; myi > ミィ; myu > ミュ; mye > ミェ; myo > ミョ;
rya > リャ; ryi > リィ; ryu > リュ; rye > リェ; ryo > リョ;
bya > ビャ; byi > ビィ; byu > ビュ; bye > ビェ; byo > ビョ;
pya > ピャ; pyi > ピィ; pyu > ピュ; pye > ピェ; pyo > ピョ;
vya > ヴャ; vyi > ヴィ; vyu > ヴュ; vye > ヴェ; vyo > ヴョ;
fya > フャ; fyi > フィ; fyu > フュ; fye > フェ; fyo > フョ;
ya > ヤ; yi > イ; yu > ユ; ye > イェ; yo > ヨ;
wa > ワ; wi > ウィ; wu > ウ; we > ウェ; wo > ウォ;
ka > カ; ki > キ; ku > ク; ke > ケ; ko > コ;
ga > ガ; gi > ギ; gu > グ; ge > ゲ; go > ゴ;
sa > サ; si > シ; su > ス; se > セ; so > ソ;
za > ザ; zi > ジ; zu > ズ; ze > ゼ; zo > ゾ;
ta > タ; ti > ティ; tu > トゥ; te > テ; to > ト;
da > ダ; di > ディ; du > ドゥ; de > デ; do > ド;
na > ナ; ni > ニ; nu > ヌ; ne > ネ; no > ノ;
ha > ハ; hi > ヒ; hu > フ; he > ヘ; ho > ホ;
pa > パ; pi > ピ; pu > プ; pe > ペ; po > ポ;
ba > バ; bi > ビ; bu > ブ; be > ベ; bo > ボ;
ma > マ; mi > ミ; mu > ム; me > メ; mo > モ;
ra > ラ; ri > リ; ru > ル; re > レ; ro > ロ;
fa > ファ; fi > フィ; fu > フ; fe > フェ; fo > フォ;
va > ヴァ; vi > ヴィ; vu > ヴ; ve > ヴェ; vo > ヴォ;
a > ア; i > イ; u > ウ; e > エ; o > オ;

ky > キ;
gy > ギ;
sy > シ;
zy > ジ;
ty > チ;
dy > ヂ;
ny > ニ;
hy > ヒ;
my > ミ;
ry > リ;
by > ビ;
py > ピ;
vy > ヴィ;
fy > フィ;

k > ク;
g > グ;
sh > シュ;
s > ス;
z > ズ;
j > ジュ;
ts > ツ;
t > ト;
d > ド;
ch > チ;
h > フ;
p > プ;
b > ブ;
m > ム;
f > フ;
v > ヴ;
r > ル;
n > ン;
y > イ;
w > ウ;
`;
