export const latnPlRules = `
::Null;

$vowels_lower = [aeiouyäöüïÿ];
$vowels_upper = [AEIOUYÄÖÜÏŸ];
$uppercase = [:Upper:];

TS > C;
Ts > C;
ts > c;
ć } [iI] > c;
Ć } [iI] > C;
ć } $vowels_lower > ci;
ć } $vowels_upper > cI;
Ć } $vowels_lower > Ci;
Ć } $vowels_upper > CI;
đ } [iI] > dz;
Đ } [iI] > Dz;
đ } $vowels_lower > dzi;
đ } $vowels_upper > dzI;
Đ } $vowels_lower > Dzi;
Đ } $vowels_upper > DZI;
$uppercase { đ > dź;
đ > dź;
Đ } $uppercase > DŹ;
$uppercase { Đ > DŹ;
Đ > Dź;
ń } [iI] > n;
Ń } [iI] > N;
ń } $vowels_lower > ni;
ń } $vowels_upper > nI;
Ń } $vowels_lower > Ni;
Ń } $vowels_upper > NI;
$uppercase { š > SZ;
š } $uppercase > SZ;
Š } $uppercase > SZ;
$uppercase { Š > SZ;
Š > Sz;
š > sz;
$uppercase { č > CZ;
č } $uppercase > CZ;
Č } $uppercase > CZ;
$uppercase { Č > CZ;
Č > Cz;
č > cz;
$uppercase { x > CH;
x } $uppercase > CH;
X } $uppercase > CH;
$uppercase { X > CH;
X > Ch;
x > ch;
ž > ż;
Ž > Ż;
ľ > l;
Ľ > L;
y > j;
Y > J;
ï > y;
Ï > Y;
v > w;
V > W;
q > k;
Q > K;
ä > e;
Ä > E;
ö > e;
Ö > E;
ü > i;
Ü > I;
ÿ > i;
Ÿ > I;
`;
