export const latnHuRules = `
::Null;

DŽDŽ } [:Lower:] > Ddzs;
DŽDŽ > DDZS;
Dždž > Ddzs;
dždž > ddzs;
DZDZ } [:Lower:] > Ddz;
DZDZ > DDZ;
Dzdz > Ddz;
dzdz > ddz;
NGNG } [:Lower:] > Nng;
NGNG > NNG;
Ngng > Nng;
ngng > nng;
KHKH } [:Lower:] > Chch;
KHKH > CHCH;
Khkh > Chch;
khkh > chch;
TSTS > CC;
Tsts > Cc;
tsts > cc;
ČČ } [:Lower:] > Ccs;
ČČ > CCS;
Čč > Ccs;
čč > ccs;
ŽŽ } [:Lower:] > Zzs;
ŽŽ > ZZS;
Žž > Zzs;
žž > zzs;
SS } [:Lower:] > Ssz;
SS > SSZ;
Ss > Ssz;
ss > ssz;
ĆĆ } [:Lower:] > Tty;
ĆĆ > TTY;
Ćć > Tty;
ćć > tty;
ĐĐ } [:Lower:] > Ggy;
ĐĐ > GGY;
Đđ > Ggy;
đđ > ggy;
XX } [:Lower:] > Chch;
XX > CHCH;
Xx > Chch;
xx > chch;
ŃŃ } [:Lower:] > Nny;
ŃŃ > NNY;
Ńń > Nny;
ńń > nny;
ĽĽ } [:Lower:] > Lly;
ĽĽ > LLY;
Ľľ > Lly;
ľľ > lly;
IJ > EJ;
Ij > Ej;
ij > ej;
NG > NG;
Ng > Ng;
ng > ng;
DZ > DZ;
Dz > Dz;
dz > dz;
DŽ } [:Lower:] > Dzs;
DŽ > DZS;
Dž > Dzs;
dž > dzs;
KH > CH;
Kh > Ch;
kh > ch;
TS > C;
Ts > C;
ts > c;
TH > T;
Th > T;
th > t;
GH > G;
Gh > G;
gh > g;
Č } [:Lower:] > Cs;
Č > CS;
č > cs;
Ž } [:Lower:] > Zs;
Ž > ZS;
ž > zs;
Ć } [:Lower:] > Ty;
Ć > TY;
ć > ty;
Đ } [:Lower:] > Gy;
Đ > GY;
đ > gy;
X } [:Lower:] > Ch;
X > CH;
x > ch;
Ń } [:Lower:] > Ny;
Ń > NY;
ń > ny;
Ľ } [:Lower:] > Ly;
Ľ > LY;
ľ > ly;
S } [:Lower:] > Sz;
S > SZ;
s > sz;
Š > S;
š > s;
Q > K;
q > k;
W > V;
w > v;
Y > J;
y > j;
Ä > E;
ä > e;
Ï > I;
ï > i;
Ÿ > Ü;
ÿ > ü;
['·] > ;

::Null;

[:^Letter:] [dD] [zZ] [sS] { [dD] [zZ] [sS] > ;
[:^Letter:] [dD] [zZ] { [dD] [zZ] > ;
[:^Letter:] [sS] [zZ] { [sS] [zZ] > ;
[:^Letter:] [cC] [sS] { [cC] [sS] > ;
[:^Letter:] [zZ] [sS] { [zZ] [sS] > ;
[:^Letter:] [gG] [yY] { [gG] [yY] > ;
[:^Letter:] [nN] [yY] { [nN] [yY] > ;
[:^Letter:] [tT] [yY] { [tT] [yY] > ;
[:^Letter:] [lL] [yY] { [lL] [yY] > ;
[:^Letter:] [bB] { [bB] > ;
[:^Letter:] [cC] { [cC] > ;
[:^Letter:] [dD] { [dD] > ;
[:^Letter:] [fF] { [fF] > ;
[:^Letter:] [gG] { [gG] > ;
[:^Letter:] [hH] { [hH] > ;
[:^Letter:] [jJ] { [jJ] > ;
[:^Letter:] [kK] { [kK] > ;
[:^Letter:] [lL] { [lL] > ;
[:^Letter:] [mM] { [mM] > ;
[:^Letter:] [nN] { [nN] > ;
[:^Letter:] [pP] { [pP] > ;
[:^Letter:] [qQ] { [qQ] > ;
[:^Letter:] [rR] { [rR] > ;
[:^Letter:] [sS] { [sS] > ;
[:^Letter:] [tT] { [tT] > ;
[:^Letter:] [vV] { [vV] > ;
[:^Letter:] [wW] { [wW] > ;
[:^Letter:] [xX] { [xX] > ;
[:^Letter:] [yY] { [yY] > ;
[:^Letter:] [zZ] { [zZ] > ;

::Null;

dzs } dzs > d;
Dzs } dzs > D;
DZS } DZS > D;
DZS } dzs > D;
dz } dz > d;
Dz } dz > D;
DZ } DZ > D;
DZ } dz > D;
sz } sz > s;
Sz } sz > S;
SZ } SZ > S;
SZ } sz > S;
cs } cs > c;
Cs } cs > C;
CS } CS > C;
CS } cs > C;
zs } zs > z;
Zs } zs > Z;
ZS } ZS > Z;
ZS } zs > Z;
gy } gy > g;
Gy } gy > G;
GY } GY > G;
GY } gy > G;
ny } ny > n;
Ny } ny > N;
NY } NY > N;
NY } ny > N;
ty } ty > t;
Ty } ty > T;
TY } TY > T;
TY } ty > T;
ly } ly > l;
Ly } ly > L;
LY } LY > L;
LY } ly > L;

::Null;

[bB] [bB] { [bB] > ;
[cC] [cC] { [cC] > ;
[dD] [dD] { [dD] > ;
[fF] [fF] { [fF] > ;
[gG] [gG] { [gG] > ;
[hH] [hH] { [hH] > ;
[jJ] [jJ] { [jJ] > ;
[kK] [kK] { [kK] > ;
[lL] [lL] { [lL] > ;
[mM] [mM] { [mM] > ;
[nN] [nN] { [nN] > ;
[pP] [pP] { [pP] > ;
[qQ] [qQ] { [qQ] > ;
[rR] [rR] { [rR] > ;
[sS] [sS] { [sS] > ;
[tT] [tT] { [tT] > ;
[vV] [vV] { [vV] > ;
[wW] [wW] { [wW] > ;
[xX] [xX] { [xX] > ;
[yY] [yY] { [yY] > ;
[zZ] [zZ] { [zZ] > ;
`;
