export const msIdRules = `
::NFC;

[mM]u { z } [iI] > s;
[mM]U { Z } [I] > S;
[tT]ele { f } [oO] > p;
[tT]ELE { F } [O] > P;
[bB]e { z } [aA] > d;
[bB]E { Z } [A] > D;
[aA]r { k } [iI] > s;
[aA]R { K } [I] > S;
[aA]rsi { b > p;
[aA]RSI { B > P;

f } aham > p;
F } aham > P;
F } AHAM > P;
f } ikir > p;
F } ikir > P;
F } IKIR > P;

bilik } ' ' [mM]andi > kamar;
Bilik } ' ' [mM]andi > Kamar;
BILIK } ' ' MANDI > KAMAR;
bilik } ' ' [tT]idur > kamar;
Bilik } ' ' [tT]idur > Kamar;
BILIK } ' ' TIDUR > KAMAR;
pejabat } ' ' [pP]os > kantor;
Pejabat } ' ' [pP]os > Kantor;
PEJABAT } ' ' POS > KANTOR;

[uU]nivers { iti > itas;
[uU]NIVERS { ITI > ITAS;
[kK]ual { iti > itas;
[kK]UAL { ITI > ITAS;
[kK]uant { iti > itas;
[kK]UANT { ITI > ITAS;
[mM]a { joriti > yoritas;
[mM]A { JORITI > YORITAS;
[mM]inor { iti > itas;
[mM]INOR { ITI > ITAS;
[fF]asil { iti > itas;
[fF]ASIL { ITI > ITAS;
[kK]omun { iti > itas;
[kK]OMUN { ITI > ITAS;
[iI] { syen > si;
[iI] { SYEN > SI;
[eE] { syen > si;
[eE] { SYEN > SI;

[:^Letter:] { Mac } [:^Letter:] > Maret;
[:^Letter:] { mac } [:^Letter:] > maret;
[:^Letter:] { MAC } [:^Letter:] > MARET;
[:^Letter:] { Jun } [:^Letter:] > Juni;
[:^Letter:] { jun } [:^Letter:] > juni;
[:^Letter:] { JUN } [:^Letter:] > JUNI;
[:^Letter:] { Julai } [:^Letter:] > Juli;
[:^Letter:] { julai } [:^Letter:] > juli;
[:^Letter:] { JULAI } [:^Letter:] > JULI;
[:^Letter:] { Ogos } [:^Letter:] > Agustus;
[:^Letter:] { ogos } [:^Letter:] > agustus;
[:^Letter:] { OGOS } [:^Letter:] > AGUSTUS;
[:^Letter:] { Disember } [:^Letter:] > Desember;
[:^Letter:] { disember } [:^Letter:] > desember;
[:^Letter:] { DISEMBER } [:^Letter:] > DESEMBER;
[:^Letter:] { Isnin > Senin;
[:^Letter:] { isnin > senin;
[:^Letter:] { ISNIN > SENIN;
[:^Letter:] { Khamis > Kamis;
[:^Letter:] { khamis > kamis;
[:^Letter:] { KHAMIS > KAMIS;
[:^Letter:] { Jumaat > Jumat;
[:^Letter:] { jumaat > jumat;
[:^Letter:] { JUMAAT > JUMAT;
[:^Letter:] { Iaitu > Yaitu;
[:^Letter:] { iaitu > yaitu;
[:^Letter:] { IAITU > YAITU;
[:^Letter:] { Kerana > Karena;
[:^Letter:] { kerana > karena;
[:^Letter:] { KERANA > KARENA;
ke { wang } an > uang;
Ke { wang } an > uang;
KE { WANG } AN > UANG;
[:^Letter:] { Wang } [:^Letter:] > Uang;
[:^Letter:] { wang } [:^Letter:] > uang;
[:^Letter:] { WANG } [:^Letter:] > UANG;
[:^Letter:] { Erti > Arti;
[:^Letter:] { erti > arti;
[:^Letter:] { ERTI > ARTI;
[:^Letter:] { Bererti > Berarti;
[:^Letter:] { bererti > berarti;
[:^Letter:] { BERERTI > BERARTI;
[:^Letter:] { Stesen > Stasiun;
[:^Letter:] { stesen > stasiun;
[:^Letter:] { STESEN > STASIUN;

::Null;

[bB] { [bB] > ;
[cC] { [cC] > ;
[dD] { [dD] > ;
[fF] { [fF] > ;
[gG] { [gG] > ;
[hH] { [hH] > ;
[jJ] { [jJ] > ;
[kK] { [kK] > ;
[lL] { [lL] > ;
[mM] { [mM] > ;
[nN] { [nN] > ;
[pP] { [pP] > ;
[qQ] { [qQ] > ;
[rR] { [rR] > ;
[sS] { [sS] > ;
[tT] { [tT] > ;
[vV] { [vV] > ;
[wW] { [wW] > ;
[xX] { [xX] > ;
[yY] { [yY] > ;
[zZ] { [zZ] > ;

[sS] [yY] { [sS] [yY] > ;
[kK] [hH] { [kK] [hH] > ;
[nN] [yY] { [nN] [yY] > ;
`;
