export const svLatnRules = `
::NFC;

[Nn] { G > G;
[Nn] { g > g;
SKJ > Š;
Skj > Š;
skj > š;
STJ > Š;
Stj > Š;
stj > š;
SCH > Š;
Sch > Š;
sch > š;
SH > Š;
Sh > Š;
sh > š;
SJ > Š;
Sj > Š;
sj > š;
TJ > Ć;
Tj > Ć;
tj > ć;
KJ > Ć;
Kj > Ć;
kj > ć;
CHR > KR;
Chr > Kr;
chr > kr;
MICH > MIK;
Mich > Mik;
mich > mik;
CH > Š;
Ch > Š;
ch > š;
CK > K;
Ck > K;
ck > k;
QU > KV;
Qu > Kv;
qu > kv;
TION > ŠON;
Tion > Šon;
tion > šon;
TH > T;
Th > T;
th > t;
PH > F;
Ph > F;
ph > f;

[^[:Letter:][:Mark:]] { DJ > J;
[^[:Letter:][:Mark:]] { Dj > J;
[^[:Letter:][:Mark:]] { dj > j;
[^[:Letter:][:Mark:]] { GJ > J;
[^[:Letter:][:Mark:]] { Gj > J;
[^[:Letter:][:Mark:]] { gj > j;
[^[:Letter:][:Mark:]] { HJ > J;
[^[:Letter:][:Mark:]] { Hj > J;
[^[:Letter:][:Mark:]] { hj > j;
[^[:Letter:][:Mark:]] { LJ > J;
[^[:Letter:][:Mark:]] { Lj > J;
[^[:Letter:][:Mark:]] { lj > j;

[Ff] [Aa] [Ll] { K } [Ee] [Nn] > K;
[Ff] [Aa] [Ll] { k } [Ee] [Nn] > k;
[Ll] [Aa] { G } [Ee] [Rr] > G;
[Ll] [Aa] { g } [Ee] [Rr] > g;
[Tt] [Aa] { G } [Ee] [Nn] > G;
[Tt] [Aa] { g } [Ee] [Nn] > g;
[Bb] [Ii] [Rr] { G } [Ii] [Tt] > G;
[Bb] [Ii] [Rr] { g } [Ii] [Tt] > g;
[Åå] { K } [Ee] > K;
[Åå] { k } [Ee] > k;

[Rr] { G } [Rr] > G;
[Rr] { g } [Rr] > g;
[Ll] { G } [Rr] > G;
[Ll] { g } [Rr] > g;
[Rr] { G } [AOUÅaouå] > G;
[Rr] { g } [AOUÅaouå] > g;
[Ll] { G } [AOUÅaouå] > G;
[Ll] { g } [AOUÅaouå] > g;
[Rr] { G > J;
[Rr] { g > j;
[Ll] { G > J;
[Ll] { g > j;

SK } [EIYÄÖÆØeiyäöæø] > Š;
Sk } [EIYÄÖÆØeiyäöæø] > Š;
sk } [EIYÄÖÆØeiyäöæø] > š;
G } [EIYÄÖÆØeiyäöæø] > J;
g } [EIYÄÖÆØeiyäöæø] > j;
C } [EIYÄÖÆØeiyäöæø] > S;
c } [EIYÄÖÆØeiyäöæø] > s;

::Null;

[AaEeOo] { Y > Y;
[AaEeOo] { y > y;
Å > O;
å > o;
Y > Ü;
y > ü;
Æ > Ä;
æ > ä;
Ø > Ö;
ø > ö;
X } [:Ll:] > Ks;
X > KS;
x > ks;
Z > S;
z > s;
W > V;
w > v;
Q > K;
q > k;
C > K;
c > k;
J > Y;
j > y;

EIJ > IJ;
Eij > Ij;
eij > ij;
EJ > IJ;
Ej > Ij;
ej > ij;
EI > IJ;
Ei > Ij;
ei > ij;
`;
