export const compoundDictionary: Record<string, string> = {
  "bắc kinh": "北京",
  "thượng hải": "上海",
  "vũ hán": "武汉",
  "trung quốc": "中国",
  "công ty": "公司",
  "cổ phần": "股份",
  "khoa kỹ": "科技",
  "trương vĩ kiệt": "张伟杰",
  "hà nội": "河内",
  "thành phố hồ chí minh": "胡志明市",
  "hải phòng": "海防",
  "đà nẵng": "岘港",
  "cần thơ": "芹苴",
  "biên hòa": "边和",
  "vũng tàu": "头顿",
  "nha trang": "芽庄",
  "buôn ma thuột": "邦美蜀",
  "quy nhơn": "归仁",
  huế: "顺化",
  "long xuyên": "龙川",
  "phan thiết": "潘切",
  "rạch giá": "迪石",
  "thủ dầu một": "土龙木",
  "nam định": "南定",
  "bạc liêu": "薄辽",
  "cà mau": "金瓯",
  "ninh bình": "宁平",
  "thái nguyên": "太原",
  "tập đoàn": "集团",
  "tổng công ty": "总公司",
  "thương mại": "商业",
  "ngân hàng": "银行",
  "viễn thông": "电信",
  "quân đội": "军队",
  "hàng không": "航空",
  "ngoại thương": "外贸",
  "nông nghiệp": "农业",
  "phát triển": "发展",
  "nông thôn": "农村",
  "đường sắt": "铁路",
  "bảo hiểm": "保险",
  "đầu tư": "投资",
  "thăm dò": "勘探",
  "khai thác": "开采",
  "dầu khí": "石油",
  "quốc gia": "国家",
  "xăng dầu": "汽油",
  "bưu điện": "邮电",
  "việt nam": "越南",
  vinamilk: "越乳",
  "sữa việt nam": "越南乳业",
  "thế giới di động": "移动世界",
  "hòa phát": "和发",
  "kinh đô": "京都",
  "bảo việt": "保越",
  masan: "马山",
  "công nghiệp": "工业",
  "công thương": "工商",
  "bánh kẹo": "糕点",
  và: "和",
  "nguyễn phan anh thư": "阮潘英书",
  "trần minh hoàng nam": "陈明黄南",
  "lê thị kim ngân": "黎氏金银",
  "phạm hồng quang dũng": "范洪光勇",
  "võ văn đức trọng": "武文德重",
  "đặng thùy minh châu": "邓垂明珠",
  "bùi hữu phước lộc": "裴有福禄",
  "ngô mỹ ngọc huyền": "吴美玉玄",
  "đỗ tuấn khải hoàn": "杜俊凯还",
  "hoàng bảo khánh an": "黄保庆安",
  "phan thanh trường giang": "潘清长江",
  "vũ diệu linh chi": "武妙灵芝",
  "cao xuân nhật minh": "高春日明",
  "mai thu phương thảo": "梅秋芳草",
  "trịnh quốc bảo lâm": "郑国保林",
  "lý thụy vân anh": "李瑞云英",
  "đinh gia thế vinh": "丁家世荣",
  "đoàn thục thùy dương": "段淑垂杨",
  "lâm vĩnh tiến đạt": "林永进达",
  "quách kiến tường vy": "郭建蔷薇",
  "công ty cổ phần": "股份公司",
  "ngân hàng thương mại cổ phần": "商业股份银行",
  "tập đoàn công nghiệp viễn thông quân đội": "军队电信工业集团",
  "tổng công ty hàng không việt nam": "越南航空总公司",
  "tổng công ty bưu điện việt nam": "越南邮电总公司",
  "ngân hàng nông nghiệp và phát triển nông thôn": "农业农村发展银行",
  "tập đoàn dầu khí quốc gia": "国家石油集团",
  "tổng công ty đường sắt việt nam": "越南铁路总公司",
  "tổng công ty thăm dò khai thác dầu khí": "石油勘探开采总公司",
  "ngân hàng công thương việt nam": "越南工商银行",
  "ngân hàng thương mại cổ phần ngoại thương": "外贸商业股份银行",
  "công ty sữa việt nam": "越南乳业公司",
  "tập đoàn xăng dầu việt nam": "越南国家石油集团",
  "công ty cổ phần thế giới di động": "移动世界股份公司",
  "tập đoàn hòa phát": "和发集团",
  "công ty cổ phần fpt": "FPT股份公司",
  "công ty cổ phần vinamilk": "越乳股份公司",
  "tập đoàn masan": "马山集团",
  "công ty cổ phần vng": "VNG股份公司",
  "công ty cổ phần bánh kẹo kinh đô": "京都糕点股份公司",
  "tổng công ty bảo hiểm bảo việt": "保越保险总公司",
  "bình dương": "平阳",
  "đồng nai": "同奈",
  "quảng ninh": "广宁",
  "thanh hóa": "清化",
  "nghệ an": "乂安",
  "bắc ninh": "北宁",
  "hải dương": "海阳",
  "hưng yên": "兴安",
  "vĩnh phúc": "永福",
  "thái bình": "太平",
  "lâm đồng": "林同",
  "đà lạt": "大叻",
  "khánh hòa": "庆和",
  "thừa thiên huế": "承天顺化",
  "quảng nam": "广南",
  "hội an": "会安",
  "bà rịa vũng tàu": "巴地头顿",
  "kiên giang": "坚江",
  "phú quốc": "富国",
  "tiền giang": "前江",
  "an giang": "安江",
  "đồng tháp": "同塔",
  "lào cai": "老街",
  "sa pa": "沙坝",
  "lạng sơn": "谅山",
  tỉnh: "省",
  "thành phố": "市",
  quận: "郡",
  huyện: "县",
  phường: "坊",
  xã: "社",
  "đồng bằng sông cửu long": "湄公河三角洲",
  "đồng bằng sông hồng": "红河三角洲",
  "tập đoàn vingroup": "温纳集团",
  "tập đoàn sun group": "太阳集团",
  "tập đoàn flc": "FLC集团",
  "tập đoàn điện lực việt nam": "越南电力集团",
  "tập đoàn than khoáng sản việt nam": "越南煤炭矿产集团",
  "tập đoàn dệt may việt nam": "越南纺织服装集团",
  "ngân hàng đầu tư và phát triển việt nam": "越南投资与发展银行",
  "ngân hàng tmcp kỹ thương việt nam": "越南技商股份商业银行",
  "ngân hàng tmcp quân đội": "军队股份商业银行",
  "ngân hàng tmcp việt nam thịnh vượng": "越南繁荣股份商业银行",
  "ngân hàng tmcp sài gòn thương tín": "西贡商信股份商业银行",
  "ngân hàng tmcp á châu": "亚洲股份商业银行",
  "công ty cổ phần vinhomes": "Vinhomes股份公司",
  "công ty hàng không vietjet": "越捷航空公司",
  "hãng hàng không bamboo airways": "竹子航空公司",
};

export const singleDictionary: Record<string, string> = {
  nam: "南",
  hải: "海",
  việt: "越",
  đại: "大",
  học: "学",
  minh: "明",
  nguyễn: "阮",
  trần: "陈",
  lê: "黎",
  phạm: "范",
  võ: "武",
  đặng: "邓",
  bùi: "裴",
  ngô: "吴",
  đỗ: "杜",
  hoàng: "黄",
  phan: "潘",
  vũ: "武",
  cao: "高",
  mai: "梅",
  trịnh: "郑",
  lý: "李",
  đinh: "丁",
  đoàn: "段",
  lâm: "林",
  quách: "郭",
  thị: "氏",
  văn: "文",
  anh: "英",
  kim: "金",
  ngân: "银",
  hồng: "红",
  quang: "光",
  dũng: "勇",
  đức: "德",
  trọng: "重",
  thùy: "垂",
  châu: "珠",
  hữu: "有",
  phước: "福",
  lộc: "禄",
  mỹ: "美",
  ngọc: "玉",
  huyền: "玄",
  huỳnh: "黄",
  hồ: "胡",
  dương: "杨",
  đào: "陶",
  tạ: "谢",
  thái: "泰",
  chu: "周",
  phùng: "冯",
  kiều: "乔",
  vương: "王",
  trương: "张",
  tôn: "孙",
  tưởng: "蒋",
  lưu: "刘",
  chung: "钟",
  tô: "苏",
  diệp: "叶",
  trang: "庄",
  lư: "卢",
  la: "罗",
  hà: "河",
  lan: "兰",
  phương: "芳",
  thảo: "草",
  thanh: "青",
  thu: "秋",
  thủy: "水",
  hương: "香",
  linh: "灵",
  hằng: "恒",
  yến: "燕",
  dung: "容",
  tuyết: "雪",
  hoa: "花",
  cúc: "菊",
  trúc: "竹",
  bích: "碧",
  nhi: "儿",
  uyên: "渊",
  thi: "诗",
  diễm: "艳",
  chi: "芝",
  my: "嵋",
  mi: "嵋",
  vân: "云",
  quỳnh: "琼",
  trâm: "簪",
  thúy: "翠",
  thụy: "瑞",
  liên: "莲",
  nhung: "绒",
  nguyệt: "月",
  trinh: "贞",
  tú: "秀",
  tài: "才",
  tuấn: "俊",
  hùng: "雄",
  thành: "成",
  đạt: "达",
  phúc: "福",
  thọ: "寿",
  tâm: "心",
  trí: "智",
  tín: "信",
  nhân: "仁",
  nghĩa: "义",
  lễ: "礼",
  phong: "风",
  sơn: "山",
  thắng: "胜",
  kiên: "坚",
  trung: "忠",
  hiếu: "孝",
  quân: "军",
  bình: "平",
  tiến: "进",
  vinh: "荣",
  huy: "辉",
  khánh: "庆",
  khoa: "科",
  tùng: "松",
  bách: "百",
  quyết: "决",
  nhật: "日",
  quốc: "国",
  bảo: "保",
  gia: "家",
  thế: "世",
  hoàn: "还",
  khải: "凯",
  cường: "强",
  long: "龙",
  phú: "富",
  kiệt: "杰",
  hậu: "厚",
  đông: "东",
  tây: "西",
  bắc: "北",
  thượng: "上",
  hạ: "下",
  tiểu: "小",
  tân: "新",
  cựu: "旧",
  giang: "江",
  biển: "海",
  đảo: "岛",
  đỉnh: "顶",
  động: "洞",
  vịnh: "湾",
  môn: "门",
  quan: "关",
  lộ: "路",
  tuyến: "线",
  cầu: "桥",
  xuân: "春",
  mộc: "木",
  hỏa: "火",
  thổ: "土",
  ninh: "宁",
  an: "安",
  hòa: "和",
  hưng: "兴",
  phát: "发",
  vượng: "旺",
  toàn: "全",
  thịnh: "盛",
  sáng: "创",
  kiến: "建",
  hiệp: "协",
  lực: "力",
  đồng: "同",
  tổng: "总",
  vạn: "万",
  sinh: "生",
  nguyên: "原",
  á: "亚",
  âu: "欧",
  và: "和",
  của: "的",
  fpt: "FPT",
  vng: "VNG",
  acb: "ACB",
  vnpt: "VNPT",
};
