import { Direction, Language, Script } from "types";

export const scripts: Record<Script, { cases: boolean; direction: Direction }> = {
  Hani: { cases: false, direction: "LTR" },
  Jpan: { cases: false, direction: "LTR" },
  Kore: { cases: false, direction: "LTR" },
  Deva: { cases: false, direction: "LTR" },
  Arab: { cases: false, direction: "RTL" },
  Hebr: { cases: false, direction: "RTL" },
  Geor: { cases: false, direction: "LTR" },
  Armn: { cases: true, direction: "LTR" },
  Grek: { cases: true, direction: "LTR" },
  Cyrl: { cases: true, direction: "LTR" },
  Latn: { cases: true, direction: "LTR" },
} as const;

export const languages: Record<Language, { script: Script }> = {
  zh: { script: "Hani" },
  ja: { script: "Jpan" },
  ko: { script: "Kore" },
  hi: { script: "Deva" },
  ar: { script: "Arab" },
  he: { script: "Hebr" },
  ka: { script: "Geor" },
  hy: { script: "Armn" },
  el: { script: "Grek" },
  ru: { script: "Cyrl" },
  uk: { script: "Cyrl" },
  bg: { script: "Cyrl" },
  mk: { script: "Cyrl" },
  az: { script: "Latn" },
  bs: { script: "Latn" },
  ca: { script: "Latn" },
  cs: { script: "Latn" },
  da: { script: "Latn" },
  de: { script: "Latn" },
  en: { script: "Latn" },
  es: { script: "Latn" },
  et: { script: "Latn" },
  fi: { script: "Latn" },
  fr: { script: "Latn" },
  hr: { script: "Latn" },
  hu: { script: "Latn" },
  id: { script: "Latn" },
  is: { script: "Latn" },
  it: { script: "Latn" },
  kk: { script: "Latn" },
  lb: { script: "Latn" },
  lt: { script: "Latn" },
  lv: { script: "Latn" },
  mt: { script: "Latn" },
  nl: { script: "Latn" },
  no: { script: "Latn" },
  pl: { script: "Latn" },
  pt: { script: "Latn" },
  ro: { script: "Latn" },
  sk: { script: "Latn" },
  sl: { script: "Latn" },
  sq: { script: "Latn" },
  sr: { script: "Latn" },
  sv: { script: "Latn" },
  tr: { script: "Latn" },
  vi: { script: "Latn" },
} as const;

export const supportedLanguages = Object.keys(languages) as Language[];
