import { Direction, Language, Script } from "types";

export const scripts: Record<Script, { cases: boolean; direction: Direction; regex: string }> = {
  Hani: { cases: false, direction: "LTR", regex: "\\p{scx=Han}\\p{M}\\p{Cf}" },
  Jpan: {
    cases: false,
    direction: "LTR",
    regex: "\\p{scx=Hiragana}\\p{scx=Katakana}\\p{scx=Han}\\p{M}\\p{Cf}",
  },
  Kore: { cases: false, direction: "LTR", regex: "\\p{scx=Hangul}\\p{M}\\p{Cf}" },
  Deva: { cases: false, direction: "LTR", regex: "\\p{scx=Devanagari}\\p{M}\\p{Cf}" },
  Arab: { cases: false, direction: "RTL", regex: "\\p{scx=Arabic}\\p{M}\\p{Cf}" },
  Hebr: { cases: false, direction: "RTL", regex: "\\p{scx=Hebrew}\\p{M}\\p{Cf}" },
  Geor: { cases: false, direction: "LTR", regex: "\\p{scx=Georgian}\\p{M}\\p{Cf}" },
  Armn: { cases: true, direction: "LTR", regex: "\\p{scx=Armenian}\\p{M}\\p{Cf}" },
  Grek: { cases: true, direction: "LTR", regex: "\\p{scx=Greek}\\p{M}\\p{Cf}" },
  Cyrl: { cases: true, direction: "LTR", regex: "\\p{scx=Cyrillic}\\p{M}\\p{Cf}" },
  Latn: { cases: true, direction: "LTR", regex: "\\p{scx=Latin}\\p{M}\\p{Cf}" },
} as const;

new RegExp(scripts["Hani"].regex, "u");

export const languages: Record<Language, { name: string; script: Script }> = {
  zh: { name: "Mandarin Chinese", script: "Hani" },
  ja: { name: "Japanese", script: "Jpan" },
  ko: { name: "Korean", script: "Kore" },
  hi: { name: "Hindi", script: "Deva" },
  ar: { name: "Arabic", script: "Arab" },
  he: { name: "Hebrew", script: "Hebr" },
  ka: { name: "Georgian", script: "Geor" },
  hy: { name: "Armenian", script: "Armn" },
  el: { name: "Greek", script: "Grek" },
  ru: { name: "Russian", script: "Cyrl" },
  uk: { name: "Ukrainian", script: "Cyrl" },
  bg: { name: "Bulgarian", script: "Cyrl" },
  mk: { name: "Macedonian", script: "Cyrl" },
  az: { name: "Azerbaijani", script: "Latn" },
  bs: { name: "Bosnian", script: "Latn" },
  ca: { name: "Catalan", script: "Latn" },
  cs: { name: "Czech", script: "Latn" },
  da: { name: "Danish", script: "Latn" },
  de: { name: "German", script: "Latn" },
  en: { name: "English", script: "Latn" },
  es: { name: "Spanish", script: "Latn" },
  et: { name: "Estonian", script: "Latn" },
  fi: { name: "Finnish", script: "Latn" },
  fr: { name: "French", script: "Latn" },
  hr: { name: "Croatian", script: "Latn" },
  hu: { name: "Hungarian", script: "Latn" },
  id: { name: "Indonesian", script: "Latn" },
  is: { name: "Icelandic", script: "Latn" },
  it: { name: "Italian", script: "Latn" },
  kk: { name: "Kazakh", script: "Latn" },
  lb: { name: "Luxembourgish", script: "Latn" },
  lt: { name: "Lithuanian", script: "Latn" },
  lv: { name: "Latvian", script: "Latn" },
  mt: { name: "Maltese", script: "Latn" },
  nl: { name: "Dutch", script: "Latn" },
  no: { name: "Norwegian", script: "Latn" },
  pl: { name: "Polish", script: "Latn" },
  pt: { name: "Portuguese", script: "Latn" },
  ro: { name: "Romanian", script: "Latn" },
  sk: { name: "Slovak", script: "Latn" },
  sl: { name: "Slovene", script: "Latn" },
  sq: { name: "Albanian", script: "Latn" },
  sr: { name: "Serbian", script: "Latn" },
  sv: { name: "Swedish", script: "Latn" },
  tr: { name: "Turkish", script: "Latn" },
  vi: { name: "Vietnamese", script: "Latn" },
} as const;

export const supportedLanguages = Object.keys(languages) as Language[];
