import { Direction, Language, Script } from "types";

export const scripts: Record<Script, { cases: boolean; direction: Direction; regex: string }> = {
  Hani: { cases: false, direction: "LTR", regex: "\\p{scx=Han}\\p{M}\\p{Cf}" },
  Jpan: {
    cases: false,
    direction: "LTR",
    regex: "\\p{scx=Hiragana}\\p{scx=Katakana}\\p{scx=Han}\\p{M}\\p{Cf}",
  },
  Kore: { cases: false, direction: "LTR", regex: "\\p{scx=Hangul}\\p{M}\\p{Cf}" },
  Deva: { cases: false, direction: "LTR", regex: "\\p{scx=Devanagari}\\p{M}\\p{Cf}" },
  Beng: { cases: false, direction: "LTR", regex: "\\p{scx=Bengali}\\p{M}\\p{Cf}" },
  Arab: { cases: false, direction: "RTL", regex: "\\p{scx=Arabic}\\p{M}\\p{Cf}" },
  Hebr: { cases: false, direction: "RTL", regex: "\\p{scx=Hebrew}\\p{M}\\p{Cf}" },
  Geor: { cases: false, direction: "LTR", regex: "\\p{scx=Georgian}\\p{M}\\p{Cf}" },
  Armn: { cases: true, direction: "LTR", regex: "\\p{scx=Armenian}\\p{M}\\p{Cf}" },
  Grek: { cases: true, direction: "LTR", regex: "\\p{scx=Greek}\\p{M}\\p{Cf}" },
  Cyrl: { cases: true, direction: "LTR", regex: "\\p{scx=Cyrillic}\\p{M}\\p{Cf}" },
  Latn: { cases: true, direction: "LTR", regex: "\\p{scx=Latin}\\p{M}\\p{Cf}" },
} as const;

export const languages: Record<Language, { name: string; script: Script; speechLocale: string }> = {
  zh: { name: "Chinese", script: "Hani", speechLocale: "zh-CN" },
  ja: { name: "Japanese", script: "Jpan", speechLocale: "ja-JP" },
  ko: { name: "Korean", script: "Kore", speechLocale: "ko-KR" },
  hi: { name: "Hindi", script: "Deva", speechLocale: "hi-IN" },
  bn: { name: "Bengali", script: "Beng", speechLocale: "bn-BD" },
  ur: { name: "Urdu", script: "Arab", speechLocale: "ur-PK" },
  fa: { name: "Persian", script: "Arab", speechLocale: "fa-IR" },
  ar: { name: "Arabic", script: "Arab", speechLocale: "ar-SA" },
  he: { name: "Hebrew", script: "Hebr", speechLocale: "he-IL" },
  ka: { name: "Georgian", script: "Geor", speechLocale: "ka-GE" },
  hy: { name: "Armenian", script: "Armn", speechLocale: "hy-AM" },
  el: { name: "Greek", script: "Grek", speechLocale: "el-GR" },
  ru: { name: "Russian", script: "Cyrl", speechLocale: "ru-RU" },
  uk: { name: "Ukrainian", script: "Cyrl", speechLocale: "uk-UA" },
  bg: { name: "Bulgarian", script: "Cyrl", speechLocale: "bg-BG" },
  mk: { name: "Macedonian", script: "Cyrl", speechLocale: "mk-MK" },
  az: { name: "Azerbaijani", script: "Latn", speechLocale: "az-AZ" },
  bs: { name: "Bosnian", script: "Latn", speechLocale: "bs-BA" },
  ca: { name: "Catalan", script: "Latn", speechLocale: "ca-ES" },
  cs: { name: "Czech", script: "Latn", speechLocale: "cs-CZ" },
  da: { name: "Danish", script: "Latn", speechLocale: "da-DK" },
  de: { name: "German", script: "Latn", speechLocale: "de-DE" },
  en: { name: "English", script: "Latn", speechLocale: "en-US" },
  es: { name: "Spanish", script: "Latn", speechLocale: "es-ES" },
  et: { name: "Estonian", script: "Latn", speechLocale: "et-EE" },
  fi: { name: "Finnish", script: "Latn", speechLocale: "fi-FI" },
  fr: { name: "French", script: "Latn", speechLocale: "fr-FR" },
  hr: { name: "Croatian", script: "Latn", speechLocale: "hr-HR" },
  hu: { name: "Hungarian", script: "Latn", speechLocale: "hu-HU" },
  id: { name: "Indonesian", script: "Latn", speechLocale: "id-ID" },
  is: { name: "Icelandic", script: "Latn", speechLocale: "is-IS" },
  it: { name: "Italian", script: "Latn", speechLocale: "it-IT" },
  kk: { name: "Kazakh", script: "Latn", speechLocale: "kk-KZ" },
  lb: { name: "Luxembourgish", script: "Latn", speechLocale: "lb-LU" },
  lt: { name: "Lithuanian", script: "Latn", speechLocale: "lt-LT" },
  lv: { name: "Latvian", script: "Latn", speechLocale: "lv-LV" },
  ms: { name: "Malay", script: "Latn", speechLocale: "ms-MY" },
  mt: { name: "Maltese", script: "Latn", speechLocale: "mt-MT" },
  nl: { name: "Dutch", script: "Latn", speechLocale: "nl-NL" },
  no: { name: "Norwegian", script: "Latn", speechLocale: "nb-NO" },
  pl: { name: "Polish", script: "Latn", speechLocale: "pl-PL" },
  pt: { name: "Portuguese", script: "Latn", speechLocale: "pt-PT" },
  ro: { name: "Romanian", script: "Latn", speechLocale: "ro-RO" },
  sk: { name: "Slovak", script: "Latn", speechLocale: "sk-SK" },
  sl: { name: "Slovene", script: "Latn", speechLocale: "sl-SI" },
  sq: { name: "Albanian", script: "Latn", speechLocale: "sq-AL" },
  sr: { name: "Serbian", script: "Latn", speechLocale: "sr-RS" },
  sv: { name: "Swedish", script: "Latn", speechLocale: "sv-SE" },
  tr: { name: "Turkish", script: "Latn", speechLocale: "tr-TR" },
  vi: { name: "Vietnamese", script: "Latn", speechLocale: "vi-VN" },
} as const;

export const supportedLanguages = Object.keys(languages) as Language[];
