export { transliterate } from "./transliterate";
export { scripts, languages } from "helpers/constants";
export { confirmLanguageByScript } from "helpers/confirmLanguageByScript";
export { type Script, type Language } from "./types";

// *** EXPERIMENTS ***

// import { transliterate } from "./transliterate";
// import { RBT } from "icu-transliterator";
// import { RBT } from "helpers/rbt";
// import { settings } from "helpers/rbt-distributor";
// import { prettyConvert } from "helpers/prettyConvert";
const test = async () => {
  /*console.log(
    await prettyConvert(
      ipaKaRules,
      `peɪ˧˩˧tɕiŋ˥˥, ʂɑŋ˥˩xaɪ˧˩˧, kuɑŋ˧˩˧ʈʂoʊ˥˥, ʂən˥˥ʈʂən˥˩, ʈʂʰəŋ˧˥tu˥˥, xɑŋ˧˥ʈʂoʊ˥˥, ɕi˥˥an˥˥, wu˧˩˧xan˥˩, nan˧˥tɕiŋ˥˥, ʈʂʰʊŋ˧˥tɕʰiŋ˥˩, su˥˥ʈʂoʊ˥˥, tʰiɛn˥˥tɕin˥˥, ʈʂʰɑŋ˧˥ʂa˥˥, tɕʰiŋ˥˥tɑʊ˧˩˧, kʰuən˥˥miŋ˧˥, ʂən˧˩˧jɑŋ˧˥, tɕi˧˩˧nan˧˥, ʈʂəŋ˥˩ʈʂoʊ˥˥, fu˧˥ʈʂoʊ˥˥, ɕia˥˩mən˧˥, ʈʂɑŋ˥˥ weɪ˧˩˧ tɕiɛ˧˥, li˧˩˧ meɪ˧˩˧liŋ˧˥, wɑŋ˧˥ tɕiɛn˥˩kuɔ˧˥, lioʊ˧˥ ɕiɑʊ˧˩˧lʊŋ˧˥, ʈʂʰən˧˥ ʈʂɨ˥˩ tɕʰiɑŋ˧˥, jɑŋ˧˥ ʂu˥˥ ʈʂən˥˥, ʈʂɑʊ˥˩ tsɨ˧˩˧ xan˧˥, xuɑŋ˧˥ tɕuən˥˩xɑʊ˧˥, ʈʂoʊ˥˥ tɕia˥˥ i˧˥, wu˧˥ miŋ˧˥ xueɪ˥˥, ɕu˧˥ wan˧˩˧ jiŋ˧˥, suən˥˥ po˧˥wən˧˥, ma˧˩˧ ɕiɑʊ˧˩˧ jan˥˩, ʈʂu˥˥ ju˧˩˧ ɕuan˥˥, xu˧˥ ʐueɪ˥˩ lin˧˥, kuɔ˥˥ məŋ˥˩ tɕi˧˥, xə˧˥ ʈʂəŋ˥˩pʰiŋ˧˥, lin˧˥ i˥˥ nuɔ˥˩, kɑʊ˥˥ ʈʂən˥˩ ju˧˩˧, luɔ˧˥ jʊŋ˧˩˧ kʰɑŋ˥˥, tʰəŋ˧˥ ɕuən˥˩ kʰə˥˥tɕi˥˩ ku˧˩˧fən˥˩ joʊ˧˩˧ɕiɛn˥˩kʊŋ˥˥sɨ˥˥, a˥˥li˧˩˧pa˥˥pa˥˥ tɕi˧˥tʰuan˧˥ kʰʊŋ˥˩ku˧˩˧ joʊ˧˩˧ɕiɛn˥˩kʊŋ˥˥sɨ˥˥, xua˧˥ weɪ˥˩ tɕi˥˩ʂu˥˩ joʊ˧˩˧ɕiɛn˥˩kʊŋ˥˥sɨ˥˥, paɪ˧˩˧tu˥˩ tsaɪ˥˩ ɕiɛn˥˩ wɑŋ˧˩˧luɔ˥˩ tɕi˥˩ʂu˥˩ joʊ˧˩˧ɕiɛn˥˩kʊŋ˥˥sɨ˥˥, tɕiŋ˥˥ tʊŋ˥˥ tɕi˧˥tʰuan˧˥ ku˧˩˧fən˥˩ joʊ˧˩˧ɕiɛn˥˩kʊŋ˥˥sɨ˥˥, meɪ˧˩˧ tʰuan˧˥ tiɛn˧˩˧ pʰiŋ˧˥ tɕi˥˩ʂu˥˩ joʊ˧˩˧ɕiɛn˥˩kʊŋ˥˥sɨ˥˥, tsɨ˥˩ tɕiɛ˧˥ tʰiɑʊ˥˩tʊŋ˥˩ kʰə˥˥tɕi˥˩ joʊ˧˩˧ɕiɛn˥˩kʊŋ˥˥sɨ˥˥, ʈʂʊŋ˥˥kuɔ˧˥ i˧˥tʊŋ˥˩ tʰʊŋ˥˥ɕin˥˩ tɕi˧˥tʰuan˧˥ joʊ˧˩˧ɕiɛn˥˩kʊŋ˥˥sɨ˥˥, ʈʂʊŋ˥˥kuɔ˧˥ tɕiɛn˥˩ʂə˥˩ jin˧˥xɑŋ˧˥ ku˧˩˧fən˥˩ joʊ˧˩˧ɕiɛn˥˩kʊŋ˥˥sɨ˥˥, ʈʂʊŋ˥˥kuɔ˧˥ ʂɨ˧˥joʊ˧˥ tʰiɛn˥˥ʐan˧˥ tɕi˥˩ tɕi˧˥tʰuan˧˥ joʊ˧˩˧ɕiɛn˥˩kʊŋ˥˥sɨ˥˥, ʈʂʊŋ˥˥kuɔ˧˥ pʰiŋ˧˥an˥˥ pɑʊ˧˩˧ɕiɛn˧˩˧ tɕi˧˥tʰuan˧˥ ku˧˩˧fən˥˩ joʊ˧˩˧ɕiɛn˥˩kʊŋ˥˥sɨ˥˥, ɕiɑʊ˧˩˧mi˧˩˧ kʰə˥˥tɕi˥˩ joʊ˧˩˧ɕiɛn˥˩ tsə˧˥ʐən˥˩ kʊŋ˥˥sɨ˥˥, liɛn˧˥ɕiɑŋ˧˩˧ tɕi˧˥tʰuan˧˥ joʊ˧˩˧ɕiɛn˥˩kʊŋ˥˥sɨ˥˥, pi˧˩˧ja˥˩ ti˧˥ ku˧˩˧fən˥˩ joʊ˧˩˧ɕiɛn˥˩kʊŋ˥˥sɨ˥˥, kə˧˥ li˥˩ tiɛn˥˩tɕi˥˩ ku˧˩˧fən˥˩ joʊ˧˩˧ɕiɛn˥˩kʊŋ˥˥sɨ˥˥, xaɪ˧˩˧ ɚ˧˩˧ ʈʂɨ˥˩ tɕia˥˥ ku˧˩˧fən˥˩ joʊ˧˩˧ɕiɛn˥˩kʊŋ˥˥sɨ˥˥, wan˥˩ kʰə˥˥ tɕi˧˩˧jə˥˩ ku˧˩˧fən˥˩ joʊ˧˩˧ɕiɛn˥˩kʊŋ˥˥sɨ˥˥, kueɪ˥˩ʈʂoʊ˥˥ mɑʊ˧˥tʰaɪ˧˥tɕioʊ˧˩˧ ku˧˩˧fən˥˩ joʊ˧˩˧ɕiɛn˥˩kʊŋ˥˥sɨ˥˥, niŋ˧˥ tə˧˥ ʂɨ˧˥taɪ˥˩ ɕin˥˥ nəŋ˧˥juan˧˥ kʰə˥˥tɕi˥˩ ku˧˩˧fən˥˩ joʊ˧˩˧ɕiɛn˥˩kʊŋ˥˥sɨ˥˥, ɕiɛ˧˥ ʈʂʰəŋ˧˥ tɕi˥˩suan˥˩ tɕi˥˥ tɕi˥˩ʂu˥˩ ʂɑŋ˥˩xaɪ˧˩˧ joʊ˧˩˧ɕiɛn˥˩kʊŋ˥˥sɨ˥˥
hokkaidoː, aomoɾi ken, toːkjoː to, kanaɡawa ken, oːsaka ɸɯ, kjoːto ɸɯ, çiroɕima ken, ɸɯkɯoka ken, okinawa ken, ɸɯdʑisan, biwako, ɕinanoɡawa, setoːtɕi ɯmi, tɕitɕibɯ tama kai kokɯɾitsɯ koːen, ɕiretokohantoː, iɕikaɾihɛija, kantoː tɕihoː, çidasanmjakɯ, kaɡoɕimawan, oɡasawaɾaɕotoː, satoː arekɯsandaː taroː, sɯzɯki eɾizabesɯ hanako, takahaɕi ɯiɾiamɯ kenitɕi, tanaka kjasaɾin joːko, itoː ben dʑa min naoki, watanabe maːɡaretto kazɯmi, jamamoto sebasɯtɕan osamɯ, nakamɯɾa vu ikɯtoɾia ɕinitɕi, kobajaɕi nikoɾasɯ keiko, katoː iza beɾa tsɯjoɕi, joɕida dʑonasan akiko, jamada kɯɾisɯ teiː na itɕiroː, sasaki ɸɯredeɾikkɯ haɾɯka, jamaɡɯtɕi dʑieniɸɯaː kenta, matsɯmoto ansoniː miki, inoːe patoɾiɕia daisɯke, kimɯɾa maɕɯː irodoɾi, hajaɕi sɯteɸɯaniː çiroɕi ɸɯtoɕi, saitoː kɯɾisɯtoɸɯaː jɯi, ɕimizɯ nataɾiː daiki, tojota dʑidoːɕa kabɯɕikiɡaiɕa, soniːɡɯɾɯːpɯ kabɯɕikiɡaiɕa, nintendoː kabɯɕikiɡaiɕa, pa na sonikkɯ hoːɾɯdeinɡɯsɯ kabɯɕikiɡaiɕa, soɸɯto bankɯ ɡɯɾɯːpɯ kabɯɕikiɡaiɕa, mitsɯbiɕi ɕoːdʑi kabɯɕikiɡaiɕa, mitsɯi bɯssan kabɯɕikiɡaiɕa, honda ɡiken koːɡjoː kabɯɕikiɡaiɕa, kabɯɕikiɡaiɕa çitatɕi seisakɯɕo, nippon denɕin denwa kabɯɕikiɡaiɕa, kabɯɕikiɡaiɕa ɸɯaːsɯto ɾi tei ɾinɡɯ, kabɯɕikiɡaiɕa ɾikɯɾɯːto hoːɾɯdeinɡɯsɯ, kabɯɕikiɡaiɕa kiːensɯ, takeda jakɯçin koːɡjoː kabɯɕikiɡaiɕa, kija non kabɯɕikiɡaiɕa, çiɡaɕinippon ɾʲokakɯ tetsɯdoː kabɯɕikiɡaiɕa, nippon koːkɯː kabɯɕikiɡaiɕa, zennihon kɯːjɯ kabɯɕikiɡaiɕa, kabɯɕikiɡaiɕa ɕi nama doː, kabɯɕikiɡaiɕa sebɯn＆ai hoːɾɯdeinɡɯsɯ
sʌul, pusan, tɛɡu, intɕʰʌn, kwaŋdʑu, tɛdʑʌn, ulsan, sedʑoŋ, kjʌŋdʑu, tɕʌndʑu, tɕedʑu, pʰjʌŋtɕʰaŋ, jʌsu, tok̚do, hallasan, nak̚doŋɡaŋ, sʌɾak̚san, kaŋhwado, suwʌn, namsan, kimtɕʰʌlsu, ijʌŋhɰi, pak̚dʑimin, tɕʌŋmindʑun, tɕʰwesʌjʌn, kaŋdoyun, tɕohayun, yundʑihu, imsʌyun, handʑuwʌn, odʑiyu, sʌdʑunho, kwʌndaɯn, hwaŋhjʌnu, andʑimin, soŋjedʑun, tɕʌnhaɯn, hoŋdʑihun, yusʌdʑin, jaŋmindʑɛ, samsʌŋdʑʌndʑa, hjʌndɛdʑadoŋtɕʰa, esɯkʰeihainik̚sɯ, eldʑidʑʌndʑa, neibʌ, kʰakʰao, pʰosɯkʰo, tɛhanhaŋɡoŋ, amoɾepʰʌsipʰik̚, kʰeitʰi, sinseɡje, nenmabɯl, ens͈isopʰɯtʰɯ, kʰupʰaŋ, ot͈uɡi, noŋsim, hanhwasollusjʌn, s͈idʑeidʑeildʑedaŋ, imatʰɯ, haibɯ
d̪ɪlliː, mʊmbəiː, koːlkaːt̪aː, t͡ʃeːnnəiː, beːŋɡəlʊɾʊ, ɦɛːd̪ɾaːbaːd̪, əɦməd̪aːbaːd̪, pʊɳeː, d͡ʒəjpʊɾ, ləkʰnəuː, kaːnpʊɾ, naːɡpʊɾ, ɪnd̪ɔːɾ, bʱoːpaːl, ʋɪʃaːkʰaːpət̪t̪ənəm, pəʈnaː, lʊd̪ʱɪjaːnaː, aːɡɾaː, ʋaːɾaːɳsiː, əmɾɪt̪səɾ, ɾaːɦʊl kʊmaːɾ ʃəɾmaː, pɾɪjaː sɪ̃ɦ jaːd̪əʋ, əmɪt̪ pəʈeːl d͡ʒoːʃiː, sneːɦaː ɡʊpt̪aː ʋəɾmaː, ʋɪkaːs mɪʃɾaː t̪ɪʋaːɾiː, neːɦaː kʊmaːɾiː t͡ʃɔːɦaːn, ɾoːɦən d̪aːs ɡʊpt̪aː, aːkaːŋkʂaː ɾaːj sɪnɦaː, sɔːɾəbʱ meːɦt̪aː əɡɾəʋaːl, kaːʋjaː ʃəɾmaː kəpuːɾ, əɾd͡ʒʊn jaːd̪əʋ ʈʰaːkʊɾ, ɾɪjaː kʰənnaː məlɪk, kɾɪʂɳaː pɾəsaːd̪ t̪ɾɪpaːʈʰiː, maːjaː d̪eːʋiː t͡ʃɔːd̪ʱɾiː, sɪd̪d̪ʱaːɾt̪ʰ naːjək ɾaːʋ, ənənjaː paːɳɖeː ʃaːɦ, ʋɪʋeːk bʱaːɾəd̪ʋaːd͡ʒ səkseːnaː, d̪iːkʂaː d͡ʒɛːn ɡoːjəl, əbʱɪʂeːk ɾəst̪oːɡiː ɡəɾɡ, saːɾaː kʰaːn ʃeːkʰ, ʈaːʈaː sə̃s, ɾɪlaːjə̃s ɪɳɖəsʈɾiːd͡ʒ, ɪnpʰoːsɪs lɪmɪʈeːɖ, eːt͡ʃsiːeːl ʈeːknoːlɔd͡ʒiːd͡ʒ, ʋɪpɾoː lɪmɪʈeːɖ, bʱaːɾt̪iː eːjɾəʈeːl, eːt͡ʃɖiːeːpʰsiː bɛːŋk, aːɪsiːaːɪsiːaːɪ bɛːŋk, sʈeːʈ bɛːŋk ɔpʰ ɪɳɖɪjaː, laːɾsən eːɳɖ ʈʊbɾoː, məɦɪnd̪ɾaː eːɳɖ məɦɪnd̪ɾaː, aːd̪ɪt̪jə bɪɾlaː ɡɾʊp, ʋeːd̪aːnt̪aː lɪmɪʈeːɖ, sən pʰaːɾmaːsjuːʈɪkəls, ɖɔ ɾeːɖɖiːd͡ʒ lɛːboːɾeːʈɾiːd͡ʒ, ʈaːɪʈən kəmpəniː, ɦɪnd̪ʊst̪aːn juːnɪliːʋəɾ, neːsleː ɪɳɖɪjaː, aːɪʈiːsiː lɪmɪʈeːɖ, bəd͡ʒaːd͡ʒ ɔʈoː, koːlɡeːʈ paːlmoːlɪʋ ɪɳɖɪjaː, bɾɪʈaːnɪjaː ɪɳɖəsʈɾiːd͡ʒ, ɖaːbəɾ ɪɳɖɪjaː, ɡoːɖɾeːd͡ʒ kəɲd͡ʒjuːməɾ pɾoːɖəkʈs
alquds, baɣdaːd, tˤannadʒa, masqatˤ, almanaːma, beɪruːt, alxartˤuːm, tilimsaːn, banɣaːzijj, ħalab, naʊaːkʃuːtˤ, dʒiːbuːtiː, sˤafaːqis, dʒabala tˤaːriq, waːdiː anneɪl, sˤilaːla, mka almakrama, ʔirbid, titˤwaːn, taʕizz, muħammad ʕabada arraħmaːn alfaːsijj, juːsif ʔibraːhiːm alħawasaniː, faːtˤuma sˤaːlaħa almirijj, saːrra dʒaːsim alɣaːmidijj, xaːlid waliːd azzahraːnijj, ʕumar ħasuna aʃʃamrijj, leɪlaː kamaːl alʕabiːdijj, zeɪnab maħmuːd arraʃiːdijj, ʕalajja ħamza albaluːʃijj, marjam seɪf annaːsˤirijj, ʔiːmaːn naːsˤara alkundurijj, fahd suleɪmaːn alʕuteɪbijj, nawwara ħamida attamiːmijj, maːdʒid ʕadnaːn assaʕdiː, riːm muniːr alqaħtˤaːnijj, badara ʕisˤaːm alħarbijj, manaː taʊfiːq addaʊsarijj, ħamida ʕiːsaː alhaːdʒirijj, liwalaʊa musaːʕid almutˤeɪrijj, saːmijj raːʔid alxaːlidijj, ʃarika annibraːs lilxadamat annaftˤijja, muʔassisa alʔufuq littudʒʒaːra alʕaːmma, masˤnaʕ arruwwaːd lisˤsˤanaːʕat aθθaqiːla, madʒmuːʕa alhilaːl lilistiθmaːrat almaːliːa, wakaːlla asˤsˤuquːr lissajjaːħa wassifr, matˤaːbiʕ attamajjuz alfannijja, muxtabarat alħeɪaː littaħaːliːl atˤtˤibbijja, madaːris alqamma alʕaːlamijja, funduq alluʔluʔa assiːaːħijj, matˤaːʕim adˤdˤjafa alʕarabijja, ʃarika albunjaːn lilmuqaːwilat alʔinʃaːʔijja, muʔassisa aθθurajjaː litˤtˤaːqa almutadʒaddida, ʃarika assanaːbil lilmuntidʒat alɣiðaːʔijja, masˤnaʕ aljaːquːt lilmudʒaʊharat, madʒmuːʕa almasaːrr lilħuluːl attaqnijja, ʃarika alʔamaːna littaʔmiːn attakaːfalaj, muʔassisa aʃʃiraːʕ lilmilaːħa albaħrijja, ʃarika alwaːħa lizzarraːʕa alħadiːθa, maktaba alħakama linnaʃr wattaʊziːʕ, ʃarika almanaːra lilxadamat alluːdʒistijja
tʰbilisi, batʰumi, kʰutʰaisi, rustʰavi, ɡori, tʰelavi, zuɡdidi, pʰotʰi, ozurɡetʰi, xaʃuri, siɣnaɣi, mt͡sʰxetʰa, axalt͡sʰixe, bord͡ʒomi, ɡurd͡ʒaani, kʼaspʼi, duʃetʰi, marneuli, laɡodexi, saɡared͡ʒo, ɡiorɡi davitʰ t͡ʃʰxeid͡ze, tʰamar ana d͡ʒavaxiʃvili, irakʼli levan kʼvarat͡sʰxelia, mariam nino abaʃid͡ze, davitʰ ɡiorɡi dart͡ʃʰiaʃvili, ana tʰamar xut͡sʰiʃvili, levan irakʼli ɡiorɡad͡ze, nino mariam t͡ʃʼelid͡ze, ɡiorɡi nikʼa pʰerad͡ze, tʰamar elene t͡ʃʰubinid͡ze, irakʼli vaxtʼaŋɡ d͡ʒanaʃia, davitʰ sandro kʰavtʰarad͡ze, mariam levan t͡sʰert͡sʰvad͡ze, ana ɡiorɡi maisurad͡ze, nikʼoloz tʰamaz berid͡ze, elene davitʰ d͡ʒiɣauri, vaxtʼaŋɡ ana t͡sʰint͡sʰad͡ze, sandro mariam mamalad͡ze, tʰamaz irakʼli xarad͡ze, nino ɡiorɡi vaʃakʼid͡ze, sakʰartʰvelos baŋkʼi, tʰbilisis avtʼobusebis satʼranspʼortʼo kʼompʼania, batʰumis zɣvis pʼortʼis martʰvis kʼompʼania, kʰutʰaisis avtʼomobilebis kʰarxana, ɡoris sursatʰis ɡadamuʃavebis kʼompʼania, pʰotʰis sazɣvao tʼranspʼortʼis kʼompʼania, zuɡdidis sopʰlis meurneobis kʼompʼania, tʰelavis ɣvinis t͡sʼarmoebis kʼompʼania, axalt͡sʰixis tʼuristʼuli saaɡentʼo, bord͡ʒomis mineraluri t͡sʼqʼlis kʼompʼania, mt͡sʰxetʰis istʼoriuli tʼurizmis kʼompʼania, rustʰavis metʼalurɡiuli kʼompʼania, siɣnaɣis sasmeli t͡sʼqʼlis t͡sʼarmoebis kʼompʼania, ozurɡetʰis t͡ʃʰais pʼlantʼat͡sʰiebis kʼompʼania, sakʰartʰvelos rkʼiniɡza, sakʰartʰvelos satʼelekʼomunikʼat͡sʰio kʼompʼania, tʰbilisis savat͡ʃʼro t͡sʰentʼri, ɡurd͡ʒaanis xilis ɡadamuʃavebis kʼompʼania, kʼaspʼis minis t͡sʼarmoebis kʼompʼania, duʃetʰis samtʰo mret͡sʼvelobis kʼompʼania, sakʰartʰvelos erovnuli baŋkʼi, tʰbilisis elekʰtʼroenerɡiis ɡanat͡sʼilebis kʼompʼania, batʰumis zɣvis pʼortʼis martʰvis kʼompʼania, kʰutʰaisis avtʼomobilebis kʰarxana, ɡoris sursatʰis ɡadamuʃavebis kʼompʼania, pʰotʰis sazɣvao tʼranspʼortʼis kʼompʼania, zuɡdidis sopʰlis meurneobis kʼompʼania, tʰelavis ɣvinis t͡sʼarmoebis kʼompʼania, axalt͡sʰixis tʼuristʼuli saaɡentʼo, bord͡ʒomis mineraluri t͡sʼqʼlis kʼompʼania, mt͡sʰxetʰis istʼoriuli tʼurizmis kʼompʼania, rustʰavis metʼalurɡiuli kʼompʼania, siɣnaɣis sasmeli t͡sʼqʼlis t͡sʼarmoebis kʼompʼania, ozurɡetʰis t͡ʃʰais pʼlantʼat͡sʰiebis kʼompʼania, sakʰartʰvelos rkʼiniɡza, sakʰartʰvelos satʼelekʼomunikʼat͡sʰio kʼompʼania, tʰbilisis savat͡ʃʼro t͡sʰentʼri, ɡurd͡ʒaanis xilis ɡadamuʃavebis kʼompʼania, kʼaspʼis minis t͡sʼarmoebis kʼompʼania, duʃetʰis samtʰo mret͡sʼvelobis kʼompʼania
ɑɾɑɾɑt, ɡɛʁɑmɑ, dɛbɛd, jɛʁɛɡnɑdzɔɾ, zɑnɡɛzuɾ, ɛdʒmiɑtsin, tʰɑlin, ʒɑjrɑvɑn, idʒevɑn, lɔri, χɔsɾɔv, tsɑʁkɑdzɔɾ, kɑpɑn, hɾɑzdɑn, dzɔɾɑɡɛt, ʁɑpʰɑn, mɑɾtuni, jɔtʰnɑʁbjuɾ, nɔjɛmbɛɾjɑn, ʃiɾɑk, ɑɾɑm vɑɾdɑni kɑɾɑpɛtjɑn, bɑɡɾɑt hɑkɔbi sɑɾɡsjɑn, ɡɑjɑnɛ ɑɾmɛni mnɑtsʰɑkɑnjɑn, dɑvitʰ rɔbɛɾti ɑvɛtisjɑn, jɛlɛnɑ suɾɛni ɡɾiɡɔɾjɑn, zɑvɛn ɡuɾɡɛni mɑɾtiɾɔsjɑn, ɛduɑɾd mikʰɑjɛli dɑniɛljɑn, tʰɑmɑɾɑ levɔni bɑʁdɑsɑɾjɑn, iʃχɑn sɑmvɛli pɔʁɔsjɑn, lusinɛ kɑɾɛni hɑɾutʰjunjɑn, χɑtʃʰik ɑʃɔti mɛlkʰɔnjɑn, tsɔvinɑɾ tiɡɾɑni nɑzɑɾjɑn, kɔɾjun ɛɾiki mɑnukjɑn, hɑsmik pɑɾujɾi tʰɔvmɑsjɑn, dzɔnik vɑzɡɛni stɛpʰɑnjɑn, ʁukɑs ɑɾtɑki pɛtɾɔsjɑn, mɑɾiɑm sevɑki ɑlɛkʰsɑnjɑn, nɑɾɛk fɛlikʰsi ɡevɔɾɡjɑn, ʃɑntʰ rɑzmiki χɑtʃʰɑtɾjɑn, vɔskɑn mɑjisi jɛnɔkʰjɑn, hɑjɑstɑn ɛlɛktɾɔniks, tsiɾɑn hɾɑtɑɾɑktʃʰutʰjun, ɑɾevɑjin tɛχnɔlɔɡiɑnɛɾ, lusin ʃinɑɾɑɾutʰjun, vɔskɛ vɑz ɡinɛɡɔɾtsɑɾɑn, bɑɾdzɾɑvɔlt tsʰɑntsʰɛɾ, kɑnɑtʃʰ ɑʃχɑɾh, pʰjunik tɛkʰstil, ɑdɑmɑnd vɔskɛɾtʃʰɑkɑn tun, sevɑn dzknɑbutsɑɾɑn, ɑɾɑɡɑts tɾɑnspɔɾt, mɑjɾ hɔʁ ɡjuʁɑtntɛsutʰjun, ɑni hjuɾɑnɔtsʰɑjin hɑmɑliɾ, tiɡɾɑn mɛts tpɑɡɾɑtun, ɛɾɛbuni bʒʃkɑkɑn kɛntɾɔn, muɾɑtsʰɑn dɛʁɑtun, hjusisɑjin pɔʁɔtɑ riɛltʰi, ɡɑrni kɑtʰnɑmtʰɛɾkʰ, vɑɾdɑnɑntsʰ ɑrɔʁdʒɑpɑhutʰjun, zɑnɡɑk ɡɾɑtun
ˈɫʌndən, ˈtoʊkiˌoʊ, ˌnaɪˈɹoʊbi, vænˈkuvɝ, ɹɪoʊ deɪ dʒəˈnɛˌɹoʊ, ˌɪstɑnˈbuɫ, ˈsɪdni, ˌmʊmˈbaɪ, ˈɹeɪkəvɪk, ˈbweɪnəs ˈɛɹiz, ˌkæsəˈbɫæŋkə, ˈɛdənbɝoʊ, ˈsɪŋəˌpɔɹ, kəθˈmændu, ˈɫɪzbən, ˈmɛksəˌkoʊ ˈsɪti, ˈæmstɝˌdæm, ˈstɑkˌhoʊɫm, viˈɛnə, ˈfɫɔɹəns, dʒeɪmz ˌæɫəɡˈzændɝ ˈstɝɫɪŋ, ɪˈɫɪzəbəθ məˈɹi mɑntˈɡʌmɹi, ˈwɪɫjəm ˈtɑməs ˈdʒɛfɝsən, ˈkæθɝən æn ˈsʌɫəvən, ˈɹɑbɝt ˈmaɪkəɫ ˈhɛndɝsən, ˈsoʊfiə ɫuˈiz ˈɹɪtʃɝdsən, ˈdeɪvɪd ˈkɹɪstəfɝ ˈwɔɫəs, ˈmɑɹɡɝɪt ɹoʊz fɪtsˈdʒɛɹəɫd, ˈbɛndʒəmən ˈɛdwɝd ˈtɑmpsən, oʊˈɫɪviə ɡɹeɪs ˈpætɝsən, ˈsæmjuɫ ˈɹɪtʃɝd ˈhɛɹɪsən, ˈɛɫənɝ dʒeɪn ˈwɪtəkɝ, ˈdʒɑnəθən ˈdeɪvɪd ˈmɪɫɝ, vɪkˈtɔɹiə ˈbiətɹəs θɔɹn, ˈnɪkəɫəs ˈɑɹθɝ ˈstɝɫɪŋ, ˌɪzəˈbɛɫə ˈmɛɹi ˈkɹɔfɝd, ˈdænjəɫ ˈpætɹɪk əˈsʌɫɪvən, ˈbiətɹəs ˈæɫəs ˈkɛnzɪŋtən, ˈhɛnɹi ˈɫɔɹəns ˈfɔknɝ, pəˈnɛɫəpi daɪˈæn ˈwɛntuɹθ, ˈɡɫoʊbəɫ ˌɪnəˈveɪʃən ˌtɛknˈɑɫədʒiz, ˈsɪɫvɝ kɹik ˌmænjəˈfæktʃɝɪŋ, həˈɹaɪzən stɹəˈtidʒɪk kənˈsʌɫtɪŋ, ˈɹeɪˌdiənt ˈɛnɝdʒi ˈsoʊɫətiənz, ˈɛmɝɹəɫd ˈvæɫi ˈæɡɹɪˌkʌɫtʃɝ, ˈnɔɹðɝn stɑɹ ˈɫoʊdʒɪstɪks, pik pɝˈfɔɹməns æθˈɫɛtɪks, bɫu ˈmɑɹbəɫ ˈɛɹoʊˌspeɪs, ˈɡoʊɫdən ɡeɪt ˈsɔfˌwɛɹ, ˈvɛɫvət θɹɛd ˈtɛkstɪɫəz, ˈkɹɪstəɫ kɫɪɹ kəmˌjunəˈkeɪʃənz, aɪɝn wɝks ˌɪnfɹəˈstɹʌktʃɝ, ˈhɑɹməni hɛɫθ ˈsɪstəmz, ˈmɪdˌnaɪt sʌn pɝˈdʌkʃənz, ˈpɹɛɹi wɪnd ɹɪˈnuəbəɫz, ɡɹænd ˈvɪstə ˌhɑspəˈtæɫəti, ˈstɝɫɪŋ bɹɪdʒ ˈfaɪˌnæns, ˈæɫpaɪn ɹɪdʒ ˈaʊtˌdɔɹ, ˈɝbən pʌɫs ˈmidiə, ˈkɹɪmzən oʊk ˈfɝnɪtʃɝ`,
      40,
    ),
  );*/
  // console.log(
  //   RBT.fromRules(esIpaRules).transliterate(
  //     "Santiago de Compostela, Sierra Nevada, Islas Canarias, Picos de Europa, Costa Brava, San Sebastián, Puerto del Rosario, Valle de Arán, Los Alcázares, Castellar de la Frontera, Arganda del Rey, Alcalá de Henares, Jerez de la Frontera, Molina de Segura, Talavera de la Reina, Santa Cruz de Tenerife, Vitoria Gasteiz, Mérida, Cuenca, Logroño, Alejandro Gabriel Rodríguez García, María Fernanda Martínez López, Juan Carlos Sánchez Ramírez, Elena Beatriz Torres Morales, Francisco Javier Ruiz Herrera, Claudia Isabel Jiménez Castro, Ricardo Andrés Ortiz Vargas, Sofía Alejandra Navarro Reyes, Gabriel Antonio Castro Paredes, Lucía Valentina Romero Méndez, Manuel Eduardo Flores Delgado, Adriana Patricia Silva Guerrero, Jorge Luis Mendoza Ibáñez, Natalia Victoria Peralta Soto, Roberto Sebastián Núñez Vega, Daniela Estefanía Ortega Rojas, Miguel Ángel Ramos Villanueva, Rosa María Campos Gallegos, Fernando Agustín Medina Suero, Silvia Raquel Aguilar Espinoza, Telefónica de España, Banco Santander Central Hispano, Petróleos Mexicanos, Construcciones y Auxiliar de Ferrocarriles, Ferrovial Construcción, Iberia Líneas Aéreas de España, Mapfre Seguros Generales, Inditex Industrias de Diseño Textil, Repsol Petróleo, Aceros de México, Transportes Aéreos Portugueses, Alimentos del Mediterráneo, Editorial Planeta, Seguros Catalana Occidente, Inmobiliaria Colonial, Cervecería Cuauhtémoc Moctezuma, Distribuidora Internacional de Alimentación, Gas Natural Fenosa, Abengoa Energía Solar, Logística de Transportes Ferroviarios",
  //   ),
  // );
  // const getTranslit = async () =>
  //   await transliterate(
  //     "Lisboa, Porto, Coimbra, Braga, Évora, Guimarães, Aveiro, Viseu, Santarém, Bragança, Castelo Branco, Portalegre, Beja, Faro, Funchal, Ponta Delgada, Setúbal, Vila Real, Guarda, Viana do Castelo, Afonso Henrique Ferreira, Beatriz Maria Santos, Carlos Eduardo Oliveira, Daniela Filipa Matos, Emanuel José Silva, Fernanda Rosa Costa, Gabriel Luís Pereira, Helena Sofia Martins, Isaac Manuel Sousa, Joana Rita Almeida, Kevin Alexandre Rocha, Luísa Maria Carvalho, Miguel Angelo Ribeiro, Nádia Patrícia Gomes, Otávio Augusto Neves, Paulo Jorge Machado, Raquel Antónia Lopes, Sebastião Nuno Duarte, Teresa Cristina Vale, Vicente Manuel Ramos, Petróleos de Portugal, Banco Comercial Português, Companhia de Seguros Fidelidade, Transportes Aéreos Portugueses, Caixa Geral de Depósitos, Distribuição Alimentar Jerónimo Martins, Corticeira Amorim Sociedade Gestora, Indústria de Motores Elétricos, Energias de Portugal, Sonae Investimentos Comerciais, Navegação Aérea de Portugal, Cimentos de Portugal, Correios de Portugal, Telecomunicações de Portugal, Imprensa Nacional Casa da Moeda, Estaleiros Navais de Viana do Castelo, Portos e Caminhos de Ferro, Sociedade Independente de Comunicação, Rádio e Televisão de Portugal, Logística de Transportes Marítimos",
  //     { from: "pt", to: "sv" },
  //   );
  // settings.JS_IMPLEMENTATION = false;
  // const cpp = await getTranslit();
  // settings.JS_IMPLEMENTATION = true;
  // const js = await getTranslit();
  // if (JSON.stringify(cpp) === JSON.stringify(js)) {
  //   console.log("IDENTICAL!");
  //   console.log(cpp);
  // } else {
  //   console.log("_NOT_ IDENTICAL!");
  //   console.log(cpp);
  //   console.log(js);
  // }
};
test();
